# @generated by cust v0.4.2 — DO NOT EDIT
# Regenerated every `cust build`. Edits are lost.
cmake_minimum_required(VERSION 3.21)
project(cust_workspace LANGUAGES C)

set(CMAKE_C_STANDARD 23)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# ---- crate: cstd (library) ----
add_library(cstd STATIC
    "/ws/target/debug/.rewrite/cstd/src/types.c"
    "/ws/target/debug/.rewrite/cstd/src/lib.c"
)
set_target_properties(cstd PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "/ws/target/debug/build/cstd"
    OUTPUT_NAME cstd
)
set_source_files_properties(
    "/ws/target/debug/.rewrite/cstd/src/lib.c"
    PROPERTIES OBJECT_DEPENDS
    "/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
)
target_compile_options(cstd PRIVATE
    "-O0"
    "-g3"
    "-fvisibility=hidden"
    "-include"
    "/ws/target/debug/prelude.h"
    "SHELL:-fplugin=/ws/target/debug/libcust_plugin.so"
    "-Wno-unknown-attributes"
)

# ---- crate: hello-cstd (binary) ----
add_executable(hello-cstd
    "/ws/target/debug/.rewrite/hello-cstd/src/main.c"
)
set_target_properties(hello-cstd PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "/ws/target/debug"
    OUTPUT_NAME hello-cstd
)
set_source_files_properties(
    "/ws/target/debug/.rewrite/hello-cstd/src/main.c"
    PROPERTIES OBJECT_DEPENDS
    "/ws/target/debug/.h-fragments/cstd/cstd__lib.cust.h;/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
)
target_include_directories(hello-cstd PRIVATE
    "/ws/target/debug/build/cstd/include"
)
target_link_libraries(hello-cstd PRIVATE
    cstd
)
target_compile_options(hello-cstd PRIVATE
    "-O0"
    "-g3"
    "-fvisibility=hidden"
    "-include"
    "/ws/target/debug/prelude.h"
    "SHELL:-fplugin=/ws/target/debug/libcust_plugin.so"
    "-Wno-unknown-attributes"
)
