# @generated by cust v0.4.2 — DO NOT EDIT
# Regenerated every `cust build`. Edits are lost.
cmake_minimum_required(VERSION 3.21)
project(cust_workspace LANGUAGES C)

set(CMAKE_C_STANDARD 23)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# ---- crate: cstd (generated rewrites) ----
add_custom_command(
    OUTPUT "/ws/target/debug/.rewrite/cstd/src/types.c"
    COMMAND "/ws/bin/cust" internal rewrite-file
            --crate-name cstd
            --in "/ws/cstd/src/types.c"
            --out "/ws/target/debug/.rewrite/cstd/src/types.c"
            --frags-dir "/ws/target/debug/.h-fragments/cstd"
            --deps-root "/ws/target/debug/deps"
            --own-lib-header "/ws/target/debug/build/cstd/include/cstd.h"
            --has-lib
    DEPENDS "/ws/cstd/src/types.c"
    VERBATIM)
add_custom_command(
    OUTPUT "/ws/target/debug/.rewrite/cstd/src/lib.c"
    COMMAND "/ws/bin/cust" internal rewrite-file
            --crate-name cstd
            --in "/ws/cstd/src/lib.c"
            --out "/ws/target/debug/.rewrite/cstd/src/lib.c"
            --frags-dir "/ws/target/debug/.h-fragments/cstd"
            --deps-root "/ws/target/debug/deps"
            --own-lib-header "/ws/target/debug/build/cstd/include/cstd.h"
            --has-lib
    DEPENDS "/ws/cstd/src/lib.c"
    VERBATIM)

# ---- crate: cstd (surface fragments) ----
add_custom_command(
    OUTPUT "/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
    COMMAND "/ws/bin/cust" internal surface-module
            --source "/ws/cstd/src/types.c"
            --surface-out "/ws/target/debug/build/cstd/types.surface.c"
            --fragment-out "/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
            --frags-dir "/ws/target/debug/.h-fragments/cstd"
            --deps-root "/ws/target/debug/deps"
            --std c23
            --cflag "-O0"
            --cflag "-g3"
            --include "/ws/cstd/src"
            --prelude "/ws/target/debug/prelude.h"
            --plugin "/ws/target/debug/libcust_plugin.so"
    DEPENDS "/ws/cstd/src/types.c"
            "/ws/target/debug/libcust_plugin.so"
    VERBATIM)
add_custom_command(
    OUTPUT "/ws/target/debug/.h-fragments/cstd/cstd__lib.cust.h"
    COMMAND "/ws/bin/cust" internal surface-module
            --source "/ws/cstd/src/lib.c"
            --surface-out "/ws/target/debug/build/cstd/lib.surface.c"
            --fragment-out "/ws/target/debug/.h-fragments/cstd/cstd__lib.cust.h"
            --frags-dir "/ws/target/debug/.h-fragments/cstd"
            --deps-root "/ws/target/debug/deps"
            --std c23
            --cflag "-O0"
            --cflag "-g3"
            --include "/ws/cstd/src"
            --prelude "/ws/target/debug/prelude.h"
            --plugin "/ws/target/debug/libcust_plugin.so"
    DEPENDS "/ws/cstd/src/lib.c"
            "/ws/target/debug/libcust_plugin.so"
            "/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
    VERBATIM)

# ---- crate: cstd (library) ----
add_library(cstd STATIC
    "/ws/target/debug/.rewrite/cstd/src/types.c"
    "/ws/target/debug/.rewrite/cstd/src/lib.c"
)
set_target_properties(cstd PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "/ws/target/debug/build/cstd"
    OUTPUT_NAME cstd
)
set_source_files_properties(
    "/ws/target/debug/.rewrite/cstd/src/lib.c"
    PROPERTIES OBJECT_DEPENDS
    "/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
)
target_compile_options(cstd PRIVATE
    "-O0"
    "-g3"
    "-fvisibility=hidden"
    "-include"
    "/ws/target/debug/prelude.h"
    "SHELL:-fplugin=/ws/target/debug/libcust_plugin.so"
    "-Wno-unknown-attributes"
)

# ---- crate: cstd (published header) ----
add_custom_command(
    OUTPUT "/ws/target/debug/build/cstd/include/cstd.h"
    COMMAND "/ws/bin/cust" internal crate-header
            --crate-name cstd
            --out "/ws/target/debug/build/cstd/include/cstd.h"
            --frag "/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
            --frag "/ws/target/debug/.h-fragments/cstd/cstd__lib.cust.h"
    DEPENDS "/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
            "/ws/target/debug/.h-fragments/cstd/cstd__lib.cust.h"
    VERBATIM)
add_custom_target(cstd_header ALL
    DEPENDS "/ws/target/debug/build/cstd/include/cstd.h")
add_dependencies(cstd cstd_header)

# ---- crate: cstd (integration test: alloc_pressure) ----
add_executable(cstd__itest__alloc_pressure EXCLUDE_FROM_ALL
    "/ws/target/debug/.rewrite/cstd/tests/alloc_pressure.c"
    "/ws/target/debug/cmake/cust_itest_main_cstd__alloc_pressure.c"
)
set_target_properties(cstd__itest__alloc_pressure PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "/ws/target/debug/test/cstd/alloc_pressure"
    OUTPUT_NAME alloc_pressure
)
target_include_directories(cstd__itest__alloc_pressure PRIVATE
    "/ws/target/debug/build/cstd/include"
)
target_link_libraries(cstd__itest__alloc_pressure PRIVATE
    cstd
)
target_compile_options(cstd__itest__alloc_pressure PRIVATE
    "-O0"
    "-g3"
    "-fvisibility=hidden"
    "-include"
    "/ws/target/debug/prelude.h"
    "SHELL:-fplugin=/ws/target/debug/libcust_plugin.so"
    "-Wno-unknown-attributes"
    "-DCUST_TEST_BUILD=1"
)

# ---- crate: cstd (integration test: basic) ----
add_executable(cstd__itest__basic EXCLUDE_FROM_ALL
    "/ws/target/debug/.rewrite/cstd/tests/basic.c"
    "/ws/target/debug/cmake/cust_itest_main_cstd__basic.c"
)
set_target_properties(cstd__itest__basic PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "/ws/target/debug/test/cstd/basic"
    OUTPUT_NAME basic
)
target_include_directories(cstd__itest__basic PRIVATE
    "/ws/target/debug/build/cstd/include"
)
target_link_libraries(cstd__itest__basic PRIVATE
    cstd
)
target_compile_options(cstd__itest__basic PRIVATE
    "-O0"
    "-g3"
    "-fvisibility=hidden"
    "-include"
    "/ws/target/debug/prelude.h"
    "SHELL:-fplugin=/ws/target/debug/libcust_plugin.so"
    "-Wno-unknown-attributes"
    "-DCUST_TEST_BUILD=1"
)

# ---- crate: cstd (check) ----
add_custom_command(
    OUTPUT "/ws/target/debug/.check/cstd/cstd__types.checked"
    COMMAND "${CMAKE_C_COMPILER}"
            "-std=c23"
            "-O0"
            "-g3"
            "-fvisibility=hidden"
            "-include"
            "/ws/target/debug/prelude.h"
            "-fplugin=/ws/target/debug/libcust_plugin.so"
            "-Wno-unknown-attributes"
            "-fsyntax-only"
            "/ws/target/debug/.rewrite/cstd/src/types.c"
    COMMAND "${CMAKE_COMMAND}" -E touch "/ws/target/debug/.check/cstd/cstd__types.checked"
    DEPENDS "/ws/target/debug/.rewrite/cstd/src/types.c"
            "/ws/target/debug/libcust_plugin.so"
    VERBATIM)
add_custom_command(
    OUTPUT "/ws/target/debug/.check/cstd/cstd__lib.checked"
    COMMAND "${CMAKE_C_COMPILER}"
            "-std=c23"
            "-O0"
            "-g3"
            "-fvisibility=hidden"
            "-include"
            "/ws/target/debug/prelude.h"
            "-fplugin=/ws/target/debug/libcust_plugin.so"
            "-Wno-unknown-attributes"
            "-fsyntax-only"
            "/ws/target/debug/.rewrite/cstd/src/lib.c"
    COMMAND "${CMAKE_COMMAND}" -E touch "/ws/target/debug/.check/cstd/cstd__lib.checked"
    DEPENDS "/ws/target/debug/.rewrite/cstd/src/lib.c"
            "/ws/target/debug/libcust_plugin.so"
            "/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
    VERBATIM)
add_custom_target(cust_check_cstd
    DEPENDS "/ws/target/debug/.check/cstd/cstd__types.checked"
            "/ws/target/debug/.check/cstd/cstd__lib.checked"
)
set_target_properties(cust_check_cstd PROPERTIES EXCLUDE_FROM_ALL TRUE)

# ---- crate: hello-cstd (generated rewrites) ----
add_custom_command(
    OUTPUT "/ws/target/debug/.rewrite/hello-cstd/src/main.c"
    COMMAND "/ws/bin/cust" internal rewrite-file
            --crate-name hello-cstd
            --in "/ws/hello-cstd/src/main.c"
            --out "/ws/target/debug/.rewrite/hello-cstd/src/main.c"
            --frags-dir "/ws/target/debug/.h-fragments/hello-cstd"
            --deps-root "/ws/target/debug/deps"
            --own-lib-header "/ws/target/debug/build/hello-cstd/include/hello-cstd.h"
            --dep cstd
    DEPENDS "/ws/hello-cstd/src/main.c"
    VERBATIM)

# ---- crate: hello-cstd (binary) ----
add_executable(hello-cstd
    "/ws/target/debug/.rewrite/hello-cstd/src/main.c"
)
set_target_properties(hello-cstd PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "/ws/target/debug"
    OUTPUT_NAME hello-cstd
)
set_source_files_properties(
    "/ws/target/debug/.rewrite/hello-cstd/src/main.c"
    PROPERTIES OBJECT_DEPENDS
    "/ws/target/debug/.h-fragments/cstd/cstd__lib.cust.h;/ws/target/debug/.h-fragments/cstd/cstd__types.cust.h"
)
target_include_directories(hello-cstd PRIVATE
    "/ws/target/debug/build/cstd/include"
)
target_link_libraries(hello-cstd PRIVATE
    cstd
)
target_compile_options(hello-cstd PRIVATE
    "-O0"
    "-g3"
    "-fvisibility=hidden"
    "-include"
    "/ws/target/debug/prelude.h"
    "SHELL:-fplugin=/ws/target/debug/libcust_plugin.so"
    "-Wno-unknown-attributes"
)

# ---- aggregate: cust_check ----
add_custom_target(cust_check
    DEPENDS cust_check_cstd
)
set_target_properties(cust_check PROPERTIES EXCLUDE_FROM_ALL TRUE)
