/* @generated by cust plugin — DO NOT EDIT */
/* Forward declarations of [[cust::pub]] items. */

struct basic_s {
    int x;
    int y;
    char tag;
};
struct bits_s {
    unsigned int hi : 4;
    unsigned int lo : 4;
    int rest;
};
struct packed_s {
    char a;
    int b;
    char c;
} __attribute__((packed));
struct aligned_s {
    int x;
} __attribute__((aligned(16)));
struct nested_anon_s {
    int kind;
    union {
        int i;
        long l;
    };
};
union simple_u {
    int i;
    float f;
};
enum kind_e {
    KIND_A = 1,
    KIND_B = 2,
    KIND_C = 4,
};
enum implicit_e {
    IMP_FIRST = 0,
    IMP_SECOND = 1,
    IMP_THIRD = 2,
};
enum byte_e : unsigned char {
    BYTE_LO = 0,
    BYTE_HI = 255,
};
