use crate::common::*;

// ─── v0.2: clang plugin ────────────────────────────────────────────

#[test]
fn check_without_plugin_hard_errors() {
    // The cust plugin is mandatory for `cust check` too: a missing
    // plugin is a hard error (the old warn-and-proceed fallback was
    // removed — a plugin-less check would skip the phase-1 AST
    // checks and could silently pass code the real check rejects).
    let (_tmp, dir) = stage("hello");
    let out = Command::new(env!("CARGO_BIN_EXE_cust"))
        .args(["check"])
        .env("CUST_PLUGIN", "/definitely/does/not/exist")
        .current_dir(&dir)
        .stdin(Stdio::null())
        .output()
        .expect("spawn cust");
    assert!(
        !out.status.success(),
        "cust check without a plugin should hard-error"
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("cust plugin (libcust_plugin.so) not found"),
        "V40D-12 wording missing:\n{stderr}"
    );
    assert!(
        stderr.contains("cargo run -p plugin-build"),
        "V40D-12 hint missing:\n{stderr}"
    );
}

#[test]
fn build_with_plugin_injects_fplugin_flag() {
    // Only meaningful when the plugin is built — skip otherwise so
    // CI without `cargo run -p plugin-build` doesn't choke.
    let Some(plugin) = plugin_path() else {
        eprintln!("plugin not built — skipping (run `cargo run -p plugin-build`)");
        return;
    };
    let (_tmp, dir) = stage("hello");
    let out = Command::new(env!("CARGO_BIN_EXE_cust"))
        .args(["build"])
        .env("CUST_PLUGIN", &plugin)
        .current_dir(&dir)
        .stdin(Stdio::null())
        .output()
        .expect("spawn cust");
    assert_success(&out);

    let cc = fs::read_to_string(dir.join("target/compile_commands.json")).unwrap();
    let expected = format!("-fplugin={}", plugin.display());
    assert!(
        cc.contains(&expected),
        "expected `{expected}` in compile_commands.json:\n{cc}"
    );
    // V40D-5: fragment headers are emitted by the dedicated
    // surface_pass (phase 1 / -fsyntax-only) and the plugin
    // hard-errors if `fragment-out` arrives during codegen.
    // `compile_commands.json` records codegen invocations, so
    // it must NOT contain the fragment-out arg.
    assert!(
        !cc.contains("-fplugin-arg-cust-fragment-out="),
        "compile_commands.json contains codegen fragment-out arg (V40D-5 violation):\n{cc}"
    );

    // Strongest proof the plugin actually ran: the fragment
    // header for the root module exists on disk (written by
    // surface_pass).
    let frag = dir.join("target/debug/.h-fragments/hello/lib.cust.h");
    assert!(
        frag.is_file(),
        "expected fragment header at {}",
        frag.display()
    );
    let body = fs::read_to_string(&frag).unwrap();
    assert!(
        body.contains("@generated by cust plugin"),
        "fragment header missing header marker:\n{body}"
    );
}

#[test]
fn plugin_emits_fragment_header_per_module() {
    // Only meaningful when the plugin is built.
    let Some(plugin) = plugin_path() else {
        eprintln!("plugin not built — skipping (run `cargo run -p plugin-build`)");
        return;
    };
    let (_tmp, dir) = stage("multi_module");
    let out = Command::new(env!("CARGO_BIN_EXE_cust"))
        .args(["build"])
        .env("CUST_PLUGIN", &plugin)
        .current_dir(&dir)
        .stdin(Stdio::null())
        .output()
        .expect("spawn cust");
    assert_success(&out);

    let frag_dir = dir.join("target/debug/.h-fragments/multi_module");
    for (qname, expected_sig) in [
        ("lib", "int32_t multi_module_total(void);"),
        ("util", "int32_t multi_module_util_get(void);"),
        ("parser", "int32_t multi_module_parser_count(void);"),
    ] {
        let f = frag_dir.join(format!("{qname}.cust.h"));
        assert!(f.is_file(), "missing fragment header {}", f.display());
        let body = fs::read_to_string(&f).unwrap();
        assert!(
            body.contains(expected_sig),
            "{}: missing signature {expected_sig:?}\n{body}",
            f.display()
        );
    }
}
