//! `CMakeLists` emission for the v0.4.2 `CMake`-driven build backend
//! (`docs/design/v0.4.2.md`).
//!
//! Slice A scope (V42D-16): this module owns three concerns and
//! nothing else.
//!
//! 1. **Emitter** — pure function `generate(&WorkspaceView) ->
//!    String`. Produces deterministic `CMakeLists`.txt bytes for
//!    the whole workspace per V42D-13 (one file, all members) and
//!    V42D-4 (byte-stable on no-input-change). Golden-file tested
//!    in `cmake_emit::tests`.
//!
//! 2. **Configure-skip stamp** — `compute_stamp` hashes the
//!    `CMakeLists` bytes **concatenated with the plugin .so bytes**
//!    per V42D-8 + RQ-V42-1. `write_if_changed` atomically writes
//!    the `CMakeLists` into place and updates the stamp only when
//!    the hash differs.
//!
//! 3. **Tool discovery** — `find_cmake` / `find_ninja` per
//!    V42D-10 / V42D-11. `cmake` is gated at the 3.21 floor;
//!    `ninja` has no version floor.
//!
//! In slice A this module is **wired but not load-bearing**:
//! `build_workspace` calls `write_if_changed` as a side effect so
//! the `CMakeLists` shows up on disk, but `compile_one_module` is
//! still what drives phase 2 — nothing reads the file or invokes
//! `cmake`. Slice B (V42D-16) replaces `compile_one_module` /
//! `compile_tree` with an `emit_and_drive_cmake()` that wires
//! this module to `Command::new(cmake)`.

use std::{
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use anyhow::{bail, Context, Result};
use sha2::{Digest, Sha256};

// ─── Emitter input model ────────────────────────────────────────

/// Whole-workspace view the emitter consumes. Owned (not borrowed
/// against the live `Workspace`) so unit tests can fabricate
/// inputs without standing up a manifest tree.
#[derive(Debug, Clone)]
pub struct WorkspaceView {
    /// cust version string baked into the `@generated by` header
    /// comment. V42D-4: version is part of the byte format and
    /// therefore part of the configure-skip stamp; a cust upgrade
    /// that changes this string churns the stamp on purpose.
    pub cust_version: String,
    /// `CMAKE_C_STANDARD` value, e.g. `"23"`. v0.4.2 hard-codes
    /// to 23 in practice (matches clang ≥ 19 default for cwork);
    /// surfaced as a field so slice B can plumb `[clang] std` /
    /// per-member overrides through later.
    pub c_standard: String,
    /// Absolute path to the cust clang plugin .so, resolved by
    /// `plugin::Plugin::discover()`. `None` is permitted so the
    /// emitter stays usable in test environments without a real
    /// plugin; slice B's `emit_and_drive_cmake` rejects it before
    /// invoking `cmake`. The path itself is no longer emitted by
    /// `generate` directly (each member bakes the plugin flag into
    /// its own `compile_options`); the field stays on
    /// `WorkspaceView` because it still feeds the configure-skip
    /// stamp (V42D-8 + RQ-V42-1: plugin bytes hash into the stamp).
    pub plugin_path: Option<PathBuf>,
    /// Members in topological (build) order: dependencies before
    /// consumers. V42D-4 + same rule the existing
    /// `Workspace::build_order` applies.
    pub members: Vec<MemberView>,
}

/// One workspace member. Slice A emits at most two `CMake` targets
/// per member: one library + one executable. Multi-bin (v0.4.4)
/// will extend `bin_sources` from `Vec<SourceFile>` to a list of
/// `(target_name, sources)` tuples; not in slice A scope.
#[derive(Debug, Clone)]
pub struct MemberView {
    /// `[package].name`. Used verbatim as the `CMake` target name.
    pub name: String,
    /// What the member produces. `LibOnly` / `BinOnly` /
    /// `LibAndBin`. Mirrors `manifest::CrateKind` but stays
    /// `CrateKind`-free at the emitter boundary so tests don't
    /// have to construct a full `Manifest`.
    pub kind: MemberKind,
    /// Lib-half sources in topological order over `#cust use
    /// crate::<mod>` edges (= the `<crate>.h` concatenation
    /// order; V42D-4). Empty when `kind` is `BinOnly`.
    pub lib_sources: Vec<SourceFile>,
    /// Bin-half sources in the same topological order. Empty
    /// when `kind` is `LibOnly`.
    pub bin_sources: Vec<SourceFile>,
    /// Absolute path the lib archive is placed in via
    /// `ARCHIVE_OUTPUT_DIRECTORY`. Preserves the
    /// `target/<profile>/build/<crate>/` layout from v0.3+
    /// (V42D-13 keeps per-crate driver outputs at their old
    /// paths even though the `CMake` tree is workspace-level).
    pub archive_output_dir: PathBuf,
    /// Include dirs the bin half needs to reach. For a
    /// lib+bin member this is the crate's own lib include dir
    /// (so `main.c` can `#include "<crate>.h"`). For pure-bin
    /// members it's typically the per-crate `build/<crate>/include/`
    /// of each workspace dep (publish-via-symlink dep view from
    /// v0.3 still works as include resolution).
    ///
    /// Order is preserved verbatim; the caller is responsible
    /// for determinism (V42D-4: callers pass topo-ordered lists).
    pub bin_include_dirs: Vec<PathBuf>,
    /// Names of other workspace members this member's bin half
    /// links against, in topological order. Lowered to
    /// `target_link_libraries(<bin> PRIVATE <dep>)` per V42D-13.
    /// Empty for lib-only members.
    pub workspace_link_deps: Vec<String>,
    /// Names of other workspace members this member's *library*
    /// half depends on, in topological order. Lowered to
    /// `target_link_libraries(<lib> PUBLIC <dep>)` so `CMake`'s
    /// `--target <lib>` walker pulls each dep into the build
    /// (`cust build -p <lib-member>` parity with Cargo). PUBLIC
    /// also propagates the link to downstream consumers, so an
    /// exe linking against `<lib>` transparently picks up the
    /// dep chain. Empty for bin-only members.
    pub lib_workspace_deps: Vec<String>,
    /// Per-target compile options applied to every TU of the
    /// member's library and executable targets via
    /// `target_compile_options(<t> PRIVATE …)`. Built by the
    /// caller from: profile cflags (opt-level, debug info,
    /// sanitisers), `[clang] extra-cflags` from the manifest,
    /// `-fvisibility=hidden`, `-include <prelude>`, and (when a
    /// plugin is present) `SHELL:-fplugin=<abs>` +
    /// `-Wno-unknown-attributes`. The emitter passes them
    /// through verbatim — each entry becomes one literal `CMake`
    /// list element. Wrap shell-significant entries (e.g. the
    /// plugin `-fplugin=…` arg) in a `SHELL:` prefix at the
    /// caller to bypass `CMake`'s de-dup / re-order pass.
    pub compile_options: Vec<String>,
    /// Absolute path the bin executable is placed in via
    /// `RUNTIME_OUTPUT_DIRECTORY`. Cargo-parity layout: bins
    /// land at `target/<profile>/<crate>/` so `cust run` finds
    /// them at the v0.3+ location. Ignored for lib-only members.
    pub runtime_output_dir: PathBuf,
    /// `CMake` target name for the bin half. For pure-bin members
    /// this equals `name`; for lib+bin it's suffixed `-bin` to
    /// avoid the `add_executable cannot create target "<name>"
    /// because another target with the same name already exists`
    /// error (`CMake` target names are workspace-unique). The bin's
    /// `OUTPUT_NAME` still emits the unsuffixed `name` so the on-
    /// disk file is `<name>` either way — only the in-`CMake`
    /// target identifier differs.
    pub bin_target_name: String,
    /// V42D-14 test executable. `Some` whenever the member has
    /// a lib half (V32D-11 — `cust test` only tests library
    /// crates; lib+bin members test their library half only).
    /// The emitter marks each test target `EXCLUDE_FROM_ALL`
    /// so `cust build` skips it; `cust test` reaches it via
    /// `cmake --build --target <crate>__test`. Same `CMakeLists`
    /// bytes either way — the V42D-8 stamp doesn't churn when
    /// flipping modes, so neither does the configure step.
    pub test_target: Option<TestTargetView>,
}

/// V42D-14 per-member test executable description. Lowered to a
/// `add_executable(<crate>__test EXCLUDE_FROM_ALL ...)` target.
/// `EXCLUDE_FROM_ALL` keeps it out of the default `cmake --build`
/// graph; `cust test` reaches it explicitly via `--target`.
#[derive(Debug, Clone)]
pub struct TestTargetView {
    /// `CMake` target name. Always `<member>__test` (V42D-14).
    pub target_name: String,
    /// Test-build sources: same lib-half `.rewrite/<crate>/src/*.c`
    /// files as the lib target, plus the driver-generated
    /// `cust_test_main_<crate>.c` runner TU.
    pub sources: Vec<SourceFile>,
    /// Include dirs the test TUs need to reach. Slice C: the
    /// member's own `build/<crate>/include/` so the runner can
    /// `#include "<crate>.h"` if needed.
    pub include_dirs: Vec<PathBuf>,
    /// Workspace deps to link against (transitive lib chain) —
    /// same shape as `MemberView::workspace_link_deps`.
    pub link_deps: Vec<String>,
    /// Per-target compile options. Same shape as
    /// `MemberView::compile_options` plus the
    /// `-DCUST_TEST_BUILD=1` define and the `cust test` plugin
    /// invocation (no different from the build-mode plugin
    /// argv except that plugin-side branches keyed on
    /// `CUST_TEST_BUILD` activate).
    pub compile_options: Vec<String>,
    /// Absolute path the test exe lands in via
    /// `RUNTIME_OUTPUT_DIRECTORY`. Slice C pins this at
    /// `target/<profile>/test/<crate>/` so the existing test
    /// runner code (and integration test fixtures) find the
    /// binary at the v0.3.2 location.
    pub runtime_output_dir: PathBuf,
}

/// Mirror of `manifest::CrateKind`, exposed at the emitter
/// boundary so unit tests can construct inputs without dragging
/// the whole manifest module in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemberKind {
    LibOnly,
    BinOnly,
    LibAndBin,
}

impl MemberKind {
    const fn has_lib(self) -> bool {
        matches!(self, Self::LibOnly | Self::LibAndBin)
    }
    const fn has_bin(self) -> bool {
        matches!(self, Self::BinOnly | Self::LibAndBin)
    }
}

/// One source file passed to `CMake`. Path is absolute; the emitter
/// quotes it directly (no `${CMAKE_CURRENT_LIST_DIR}` rewriting —
/// the caller has already resolved everything).
#[derive(Debug, Clone)]
pub struct SourceFile {
    /// Absolute path to the post-`#cust use`-rewrite source file
    /// (`target/<profile>/.rewrite/<crate>/<…>.c` once slice B
    /// moves the rewrite output there; today's preprocessed
    /// path works equally well at slice A since the emitter
    /// isn't load-bearing).
    pub path: PathBuf,
    /// Absolute paths to fragment headers this TU imports via
    /// `#cust use crate::<importee>`, in topological order over
    /// the dep edges (V42D-4 + V42D-6). Empty for TUs with no
    /// cross-module imports. Lowered to a `CMake`
    /// `set_source_files_properties(... OBJECT_DEPENDS ...)`
    /// block per V42D-6.
    pub object_depends: Vec<PathBuf>,
}

// ─── Emitter ────────────────────────────────────────────────────

/// Render the workspace `CMakeLists` for `view`. Pure function;
/// determinism is the caller's responsibility (the emitter
/// preserves the orders it's handed).
///
/// Output shape pinned by the golden file at
/// `src/cmake_emit/testdata/cwork.cmake` (V42D-4).
#[must_use]
pub fn generate(view: &WorkspaceView) -> String {
    let mut out = String::new();

    // Header (V42D-4: cust version in `@generated`, no timestamp).
    let _ = writeln!(
        out,
        "# @generated by cust v{} — DO NOT EDIT",
        view.cust_version,
    );
    out.push_str("# Regenerated every `cust build`. Edits are lost.\n");
    out.push_str("cmake_minimum_required(VERSION 3.21)\n");
    out.push_str("project(cust_workspace LANGUAGES C)\n");
    out.push('\n');
    let _ = writeln!(out, "set(CMAKE_C_STANDARD {})", view.c_standard);
    out.push_str("set(CMAKE_C_STANDARD_REQUIRED ON)\n");
    out.push_str("set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n");

    // Per-member blocks.
    for m in &view.members {
        if m.kind.has_lib() {
            emit_library(&mut out, m);
        }
        if m.kind.has_bin() {
            emit_executable(&mut out, m);
        }
        if let Some(t) = &m.test_target {
            emit_test_executable(&mut out, m, t);
        }
    }

    out
}

fn emit_library(out: &mut String, m: &MemberView) {
    out.push('\n');
    let _ = writeln!(out, "# ---- crate: {} (library) ----", m.name);
    let _ = writeln!(out, "add_library({} STATIC", m.name);
    for src in &m.lib_sources {
        let _ = writeln!(out, "    \"{}\"", src.path.display());
    }
    out.push_str(")\n");
    let _ = writeln!(out, "set_target_properties({} PROPERTIES", m.name);
    let _ = writeln!(
        out,
        "    ARCHIVE_OUTPUT_DIRECTORY \"{}\"",
        m.archive_output_dir.display(),
    );
    let _ = writeln!(out, "    OUTPUT_NAME {}", m.name);
    out.push_str(")\n");
    emit_object_depends(out, &m.lib_sources);
    if !m.lib_workspace_deps.is_empty() {
        let _ = writeln!(out, "target_link_libraries({} PUBLIC", m.name);
        for dep in &m.lib_workspace_deps {
            let _ = writeln!(out, "    {dep}");
        }
        out.push_str(")\n");
    }
    emit_compile_options(out, &m.name, &m.compile_options);
}

fn emit_executable(out: &mut String, m: &MemberView) {
    out.push('\n');
    let _ = writeln!(out, "# ---- crate: {} (binary) ----", m.name);
    let _ = writeln!(out, "add_executable({}", m.bin_target_name);
    for src in &m.bin_sources {
        let _ = writeln!(out, "    \"{}\"", src.path.display());
    }
    out.push_str(")\n");
    let _ = writeln!(
        out,
        "set_target_properties({} PROPERTIES",
        m.bin_target_name
    );
    let _ = writeln!(
        out,
        "    RUNTIME_OUTPUT_DIRECTORY \"{}\"",
        m.runtime_output_dir.display(),
    );
    let _ = writeln!(out, "    OUTPUT_NAME {}", m.name);
    out.push_str(")\n");
    emit_object_depends(out, &m.bin_sources);
    if !m.bin_include_dirs.is_empty() {
        let _ = writeln!(
            out,
            "target_include_directories({} PRIVATE",
            m.bin_target_name
        );
        for dir in &m.bin_include_dirs {
            let _ = writeln!(out, "    \"{}\"", dir.display());
        }
        out.push_str(")\n");
    }
    if !m.workspace_link_deps.is_empty() {
        let _ = writeln!(out, "target_link_libraries({} PRIVATE", m.bin_target_name);
        for dep in &m.workspace_link_deps {
            let _ = writeln!(out, "    {dep}");
        }
        out.push_str(")\n");
    }
    emit_compile_options(out, &m.bin_target_name, &m.compile_options);
}

/// V42D-14: emit one test target per member that has tests,
/// marked `EXCLUDE_FROM_ALL` so `cmake --build` (the `cust
/// build` path) skips it. `cust test` reaches the target
/// explicitly via `cmake --build --target <crate>__test`. The
/// target is emitted unconditionally — same `CMakeLists` bytes
/// regardless of build vs test mode — so flipping modes doesn't
/// churn the V42D-8 stamp and never triggers a reconfigure.
fn emit_test_executable(out: &mut String, m: &MemberView, t: &TestTargetView) {
    out.push('\n');
    let _ = writeln!(out, "# ---- crate: {} (test) ----", m.name);
    let _ = writeln!(out, "add_executable({} EXCLUDE_FROM_ALL", t.target_name);
    for src in &t.sources {
        let _ = writeln!(out, "    \"{}\"", src.path.display());
    }
    out.push_str(")\n");
    let _ = writeln!(out, "set_target_properties({} PROPERTIES", t.target_name);
    let _ = writeln!(
        out,
        "    RUNTIME_OUTPUT_DIRECTORY \"{}\"",
        t.runtime_output_dir.display(),
    );
    let _ = writeln!(out, "    OUTPUT_NAME {}", m.name);
    out.push_str(")\n");
    // OBJECT_DEPENDS for the test target's sources (V42D-6).
    // Test TUs re-import the same fragment headers the lib TUs do.
    emit_object_depends(out, &t.sources);
    if !t.include_dirs.is_empty() {
        let _ = writeln!(out, "target_include_directories({} PRIVATE", t.target_name);
        for dir in &t.include_dirs {
            let _ = writeln!(out, "    \"{}\"", dir.display());
        }
        out.push_str(")\n");
    }
    if !t.link_deps.is_empty() {
        let _ = writeln!(out, "target_link_libraries({} PRIVATE", t.target_name);
        for dep in &t.link_deps {
            let _ = writeln!(out, "    {dep}");
        }
        out.push_str(")\n");
    }
    if !t.compile_options.is_empty() {
        let _ = writeln!(out, "target_compile_options({} PRIVATE", t.target_name);
        for opt in &t.compile_options {
            let _ = writeln!(out, "    \"{opt}\"");
        }
        out.push_str(")\n");
    }
}

/// Emit `target_compile_options(<target> PRIVATE …)` with one
/// option per line. Each option is written verbatim (`CMake` list
/// element); the caller wraps shell-significant strings in
/// `SHELL:` (V42D-5).
fn emit_compile_options(out: &mut String, target: &str, opts: &[String]) {
    if opts.is_empty() {
        return;
    }
    let _ = writeln!(out, "target_compile_options({target} PRIVATE");
    for opt in opts {
        // Quote every option so spaces / shell metacharacters
        // pass through cleanly. CMake unquotes them when
        // building the argv (and SHELL: prefixes survive the
        // unquote).
        let _ = writeln!(out, "    \"{opt}\"");
    }
    out.push_str(")\n");
}

/// Emit a `set_source_files_properties(... OBJECT_DEPENDS ...)`
/// block for every source with non-empty `object_depends`
/// (V42D-6). One block per source, semicolon-joined fragment
/// list. Sources with empty deps emit nothing.
fn emit_object_depends(out: &mut String, sources: &[SourceFile]) {
    for src in sources {
        if src.object_depends.is_empty() {
            continue;
        }
        out.push_str("set_source_files_properties(\n");
        let _ = writeln!(out, "    \"{}\"", src.path.display());
        out.push_str("    PROPERTIES OBJECT_DEPENDS\n    \"");
        for (i, dep) in src.object_depends.iter().enumerate() {
            if i > 0 {
                out.push(';');
            }
            let _ = write!(out, "{}", dep.display());
        }
        out.push_str("\"\n)\n");
    }
}

// ─── Configure-skip stamp (V42D-8 + RQ-V42-1) ───────────────────

/// 32-byte SHA-256. Newtype so calling code can't mix it up with
/// arbitrary byte buffers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Stamp([u8; 32]);

impl Stamp {
    /// Lowercase hex representation, suitable for writing into
    /// the stamp file.
    #[must_use]
    pub fn to_hex(self) -> String {
        let mut out = String::with_capacity(64);
        for b in self.0 {
            let _ = write!(out, "{b:02x}");
        }
        out
    }

    /// Parse a 64-char lowercase hex string. Returns `None` on
    /// any malformed input (wrong length, non-hex character, etc.)
    /// — callers treat that the same as a missing stamp file:
    /// stamp mismatch ⇒ force reconfigure.
    #[must_use]
    #[allow(dead_code)] // consumed by tests; slice B reads the stamp at configure time
    pub fn from_hex(s: &str) -> Option<Self> {
        if s.len() != 64 {
            return None;
        }
        let mut bytes = [0u8; 32];
        for (i, b) in bytes.iter_mut().enumerate() {
            let hi = hex_nibble(s.as_bytes()[i * 2])?;
            let lo = hex_nibble(s.as_bytes()[i * 2 + 1])?;
            *b = (hi << 4) | lo;
        }
        Some(Self(bytes))
    }
}

const fn hex_nibble(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        _ => None,
    }
}

/// SHA-256 of `cmakelists_bytes` concatenated with the bytes of
/// the file at `plugin_path` (V42D-8 + RQ-V42-1). The plugin's
/// path is already part of the `CMakeLists` (V42D-5 bakes it), so
/// a path change already churns the stamp via `cmakelists_bytes`;
/// hashing the plugin's *contents* closes the same-path-different-
/// .so gap that path-only hashing misses.
///
/// `plugin_path = None` (slice A no-plugin case) omits the plugin
/// chunk entirely. This is consistent: when there's no plugin in
/// the `CMakeLists`, there's no plugin contribution to hash either.
pub fn compute_stamp(cmakelists_bytes: &[u8], plugin_path: Option<&Path>) -> Result<Stamp> {
    let mut hasher = Sha256::new();
    hasher.update(cmakelists_bytes);
    if let Some(path) = plugin_path {
        let plugin_bytes = fs::read(path)
            .with_context(|| format!("reading plugin `{}` for stamp", path.display()))?;
        hasher.update(&plugin_bytes);
    }
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest);
    Ok(Stamp(out))
}

/// Result of `write_if_changed`. Slice A doesn't act on the
/// variant (the write is purely a side effect); slice B will
/// branch on it to decide whether to skip `cmake -G Ninja`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WriteOutcome {
    /// `CMakeLists` + stamp were already up to date; nothing
    /// touched on disk. Slice B uses this to skip the configure
    /// step (V42D-8).
    Unchanged,
    /// `CMakeLists` was (re)written and the stamp updated. Slice
    /// B uses this to require a `cmake -G Ninja` run.
    Wrote,
}

/// Atomically write `cmakelists_bytes` to `cmakelists_path` and
/// the new stamp to `stamp_path` iff the recomputed stamp
/// differs from the on-disk stamp (V42D-8).
///
/// Creates parent directories as needed. The `CMakeLists` and the
/// stamp are both written via `<path>.tmp` + `rename` so a crash
/// mid-write doesn't leave a desynced pair on disk.
pub fn write_if_changed(
    cmakelists_path: &Path,
    cmakelists_bytes: &[u8],
    stamp_path: &Path,
    plugin_path: Option<&Path>,
) -> Result<WriteOutcome> {
    let new_stamp = compute_stamp(cmakelists_bytes, plugin_path)?;

    // Read existing stamp; treat any read/parse failure as
    // "stamp absent → must reconfigure" (matches the design's
    // permissive shape — we never refuse to build because the
    // stamp file is corrupt).
    let existing = fs::read_to_string(stamp_path)
        .ok()
        .and_then(|s| Stamp::from_hex(s.trim()));

    if existing == Some(new_stamp) && cmakelists_path.is_file() {
        return Ok(WriteOutcome::Unchanged);
    }

    if let Some(parent) = cmakelists_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
    }
    if let Some(parent) = stamp_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
    }

    write_atomically(cmakelists_path, cmakelists_bytes)?;
    write_atomically(stamp_path, new_stamp.to_hex().as_bytes())?;
    Ok(WriteOutcome::Wrote)
}

fn write_atomically(path: &Path, bytes: &[u8]) -> Result<()> {
    let tmp = path.with_extension({
        let mut ext = path
            .extension()
            .map(|e| e.to_string_lossy().into_owned())
            .unwrap_or_default();
        if !ext.is_empty() {
            ext.push('.');
        }
        ext.push_str("tmp");
        ext
    });
    fs::write(&tmp, bytes).with_context(|| format!("writing `{}`", tmp.display()))?;
    fs::rename(&tmp, path)
        .with_context(|| format!("renaming `{}` to `{}`", tmp.display(), path.display()))?;
    Ok(())
}

// ─── Tool discovery (V42D-10 / V42D-11) ─────────────────────────
//
// Slice A defines + tests the discovery surface. Slice B
// (V42D-16's `emit_and_drive_cmake`) is the first caller. The
// `#[allow(dead_code)]` blocks below mark the surface as
// intentionally-unused-until-slice-B; they go away when slice B
// lands.

/// Resolved external tool — absolute path + parsed `--version`.
#[derive(Debug, Clone)]
#[allow(dead_code)] // consumed by slice B
pub struct Tool {
    /// Absolute path the PATH lookup resolved to.
    pub path: PathBuf,
    /// `(major, minor, patch)`. Patch is 0 when the `--version`
    /// output omits it (some `Ninja` builds report `1.11`).
    pub version: (u32, u32, u32),
}

/// Minimum `CMake` version per V42D-9.
#[allow(dead_code)] // consumed by slice B via find_cmake
const CMAKE_MIN: (u32, u32, u32) = (3, 21, 0);

/// Look up `cmake` on `$PATH`, run `cmake --version`, parse the
/// first line, enforce the 3.21 floor (V42D-9 / V42D-10).
///
/// In slice A this is **defined and tested but not called from
/// the build path** — slice B's `emit_and_drive_cmake()` is the
/// first consumer. Surfaced now so the discovery surface is in
/// place when slice B lands.
#[allow(dead_code)] // consumed by slice B
pub fn find_cmake() -> Result<Tool> {
    let tool = find_tool("cmake", CMAKE_INSTALL_HINT)?;
    if tool.version < CMAKE_MIN {
        bail!(
            "found `cmake` at `{}` reporting version {}.{}.{}, but cust v0.4.2+ \
             requires cmake >= {}.{}.{}\n{}",
            tool.path.display(),
            tool.version.0,
            tool.version.1,
            tool.version.2,
            CMAKE_MIN.0,
            CMAKE_MIN.1,
            CMAKE_MIN.2,
            CMAKE_INSTALL_HINT,
        );
    }
    Ok(tool)
}

/// Look up `ninja` on `$PATH`, run `ninja --version`, parse it.
/// No version floor (V42D-11 — `Ninja`'s build-format compat is
/// excellent). Surfaced now (slice B will be the first caller).
#[allow(dead_code)] // consumed by slice B
pub fn find_ninja() -> Result<Tool> {
    find_tool("ninja", NINJA_INSTALL_HINT)
}

const CMAKE_INSTALL_HINT: &str = "\
  hint: cust v0.4.2+ requires cmake >= 3.21 as a build-time dependency
        Linux:   apt install cmake     (or your distro's equivalent)
        macOS:   brew install cmake
        Windows: install from https://cmake.org/download/
  note: see docs/design/v0.4.2.md for the rationale";

const NINJA_INSTALL_HINT: &str = "\
  hint: cust v0.4.2+ requires ninja as a build-time dependency
        Linux:   apt install ninja-build
        macOS:   brew install ninja
        Windows: install from https://ninja-build.org/
  note: see docs/design/v0.4.2.md for the rationale";

#[allow(dead_code)] // consumed by slice B via find_cmake / find_ninja
fn find_tool(tool: &str, install_hint: &str) -> Result<Tool> {
    let output = Command::new(tool)
        .arg("--version")
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output();
    let output = match output {
        Ok(o) => o,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            bail!("error: `{tool}` not found on PATH\n{install_hint}")
        }
        Err(e) => return Err(e).with_context(|| format!("invoking `{tool} --version`")),
    };
    if !output.status.success() {
        bail!("`{tool} --version` exited with status {}", output.status);
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let first_line = stdout.lines().next().unwrap_or("");
    let version = parse_version(first_line)
        .with_context(|| format!("parsing `{tool} --version` first line: `{first_line}`"))?;
    // PATH lookup completed via Command::new, but we don't get
    // the absolute path back directly. Re-resolve via `which`-
    // equivalent: spawn `command -v <tool>` is shell-specific;
    // simpler: just record the bare tool name and let downstream
    // `Command::new(&tool.path)` re-resolve. Same posture as the
    // existing `clang::Clang::path` field.
    Ok(Tool {
        path: PathBuf::from(tool),
        version,
    })
}

/// Parse a `<tool> --version` first line. Looks for the first
/// `MAJOR.MINOR[.PATCH]` sequence and returns it. `CMake`'s first
/// line is `cmake version 3.28.1`; `Ninja`'s is just `1.11.1`.
#[allow(dead_code)] // consumed by slice B via find_tool
fn parse_version(line: &str) -> Result<(u32, u32, u32)> {
    let mut chars = line.char_indices().peekable();
    while let Some(&(start, c)) = chars.peek() {
        if c.is_ascii_digit() {
            // Walk while [0-9.] keeps making sense.
            let mut end = start;
            for (i, ch) in line[start..].char_indices() {
                if ch.is_ascii_digit() || ch == '.' {
                    end = start + i + ch.len_utf8();
                } else {
                    break;
                }
            }
            let candidate = &line[start..end];
            if let Some(v) = try_triple(candidate) {
                return Ok(v);
            }
            // Skip this run and keep looking.
            chars.nth(end - start - 1);
            continue;
        }
        chars.next();
    }
    bail!("no MAJOR.MINOR[.PATCH] found in `{line}`")
}

#[allow(dead_code)] // consumed by slice B via parse_version
fn try_triple(s: &str) -> Option<(u32, u32, u32)> {
    let mut parts = s.split('.').map(str::parse::<u32>);
    let major = parts.next()?.ok()?;
    let minor = parts.next()?.ok()?;
    let patch = parts.next().and_then(Result::ok).unwrap_or(0);
    Some((major, minor, patch))
}

// ─── Workspace → WorkspaceView bridge (slice A wire-up) ─────────

use crate::{
    manifest::{CrateKind, Manifest},
    modules,
    plugin::Plugin,
    profile::{ProfileKind, ResolvedProfile},
    target_layout::TargetLayout,
    workspace::Workspace,
};

/// Walk `ws` and produce a `WorkspaceView` describing every
/// member's lib/bin shape, sources (post-`#cust use` rewrite
/// paths), `OBJECT_DEPENDS` fragment edges, per-target compile
/// options, and output directories.
///
/// Slice B (V42D-16) is the first real consumer: the emitter
/// drives a `cmake -G Ninja` + `cmake --build` invocation
/// against the result. Walk is deterministic — same inputs in,
/// same `WorkspaceView` out, byte-stable through `generate`.
///
/// The view always contains every workspace member, regardless of
/// `cust build -p <name>` scoping (V42D-13: one `CMakeLists` for
/// the whole workspace; `-p` lowers at `cmake --build --target`
/// time, not at emit time). This keeps the stamp stable across
/// `-p` variations.
///
/// When the member has a lib half, the view always also carries
/// a populated `test_target` (V42D-14). The emitter marks the
/// test target `EXCLUDE_FROM_ALL` so the same `CMakeLists`
/// serves both `cust build` and `cust test` — only the
/// `cmake --build --target` selection on the build step
/// differs. The V42D-8 stamp is therefore stable across mode
/// flips, and `CMake` doesn't reconfigure when toggling between
/// build and test in the same workspace.
pub fn collect_view(
    ws: &Workspace,
    profile_kind: ProfileKind,
    plugin: Option<&Plugin>,
) -> Result<WorkspaceView> {
    let layout = TargetLayout::for_workspace(&ws.root, profile_kind);
    let rewrite_root = layout.profile_root.join(".rewrite");
    let prelude_path = layout.prelude_path();
    // V42D-14: cust_test_main_<crate>.c files live under the
    // workspace CMake dir so they're alongside the CMakeLists
    // that references them.
    let cmake_dir = layout.profile_root.join("cmake");

    let mut members: Vec<MemberView> = Vec::with_capacity(ws.members.len());
    for m in &ws.members {
        let kind = map_kind(&m.kind);
        let lib_sources = match m.kind.lib_source() {
            Some(src) => collect_sources(&m.root, src, &m.name, &rewrite_root, &layout)?,
            None => Vec::new(),
        };
        let bin_sources = match m.kind.bin_source() {
            Some(src) => collect_sources(&m.root, src, &m.name, &rewrite_root, &layout)?,
            None => Vec::new(),
        };

        // Bin half include dirs: for a lib+bin member, the bin
        // needs the lib's own include dir for `#include "<crate>.h"`
        // (matches the existing `compile_one_module` extra_includes
        // shape). Cross-crate dep headers are reached via the
        // absolute paths baked by `#cust use <dep>` lowering, not
        // via `target_include_directories`.
        let bin_include_dirs = if kind == MemberKind::LibAndBin {
            vec![layout
                .crate_header_path(&m.name)
                .parent()
                .unwrap()
                .to_path_buf()]
        } else {
            Vec::new()
        };

        // Intra-workspace link deps for the bin half (V42D-13:
        // lower to `target_link_libraries`). Workspace deps come
        // from `Member::deps`; for lib+bin we additionally link
        // against the member's own lib half (which still has the
        // unsuffixed member name as its CMake target).
        let mut workspace_link_deps = m.deps.clone();
        if kind == MemberKind::LibAndBin {
            workspace_link_deps.insert(0, m.name.clone());
        }

        // CMake target name for the bin half. Suffix `-bin` only
        // when the member is lib+bin, so the pure-bin case
        // (cwork hello-cstd) stays simple.
        let bin_target_name = if kind == MemberKind::LibAndBin {
            format!("{}-bin", m.name)
        } else {
            m.name.clone()
        };

        // Per-target compile options. Mirror what `build::build_cflags`
        // would produce for a non-test, non-syntax-only TU minus the
        // trailing `-c -o <obj> <src>` (CMake supplies those).
        let profile_override = match profile_kind {
            ProfileKind::Dev => m.manifest.profile.dev.as_ref(),
            ProfileKind::Release => m.manifest.profile.release.as_ref(),
        };
        let profile = ResolvedProfile::resolve(profile_kind, profile_override)?;
        let compile_options =
            build_member_compile_options(&profile, &m.manifest, &prelude_path, plugin);

        // V42D-14 test target (whenever the member has a lib
        // half). Always populated so the emitted CMakeLists is
        // identical between `cust build` and `cust test`;
        // `EXCLUDE_FROM_ALL` on the target keeps it out of the
        // default build graph.
        let test_target = if kind.has_lib() {
            // Lib-half sources (same as the lib target) plus the
            // driver-generated runner TU. The runner path is the
            // contract V42D-14 pins: cmake_dir/cust_test_main_<crate>.c.
            let mut sources = lib_sources.clone();
            sources.push(SourceFile {
                path: cmake_dir.join(format!("cust_test_main_{}.c", m.name)),
                object_depends: Vec::new(),
            });
            let mut test_opts = compile_options.clone();
            // The CUST_TEST_BUILD=1 macro is the existing v0.3.2
            // signal that activates the prelude's test branch +
            // makes the plugin attach normal external linkage to
            // [[cust::test]] decls (so the runner TU's extern
            // forward declarations can reach them).
            test_opts.push("-DCUST_TEST_BUILD=1".to_string());
            let include_dirs = vec![layout
                .crate_header_path(&m.name)
                .parent()
                .unwrap()
                .to_path_buf()];
            Some(TestTargetView {
                target_name: format!("{}__test", m.name),
                sources,
                include_dirs,
                // Test exes link against the same lib deps as the
                // member's bin half — workspace deps in topo
                // order.
                link_deps: m.deps.clone(),
                compile_options: test_opts,
                runtime_output_dir: layout.test_build_dir(&m.name),
            })
        } else {
            None
        };

        members.push(MemberView {
            name: m.name.clone(),
            kind,
            lib_sources,
            bin_sources,
            archive_output_dir: layout.build_dir(&m.name),
            runtime_output_dir: layout.profile_root.clone(),
            bin_include_dirs,
            workspace_link_deps,
            lib_workspace_deps: if kind.has_lib() {
                m.deps.clone()
            } else {
                Vec::new()
            },
            compile_options,
            bin_target_name,
            test_target,
        });
    }

    Ok(WorkspaceView {
        cust_version: env!("CARGO_PKG_VERSION").to_string(),
        c_standard: "23".to_string(),
        plugin_path: plugin.map(|p| p.path.clone()),
        members,
    })
}

/// Build the per-target compile options for one member matching
/// what the v0.4.0 driver's `build_cflags` produced (minus the
/// trailing `-c -o <obj> <src>` that `CMake` supplies). Output is a
/// flat list of `CMake` list elements; multi-word flags like
/// `-include <path>` are emitted as two separate elements so
/// `CMake`'s argv reconstruction passes them to clang verbatim.
fn build_member_compile_options(
    profile: &ResolvedProfile,
    manifest: &Manifest,
    prelude: &Path,
    plugin: Option<&Plugin>,
) -> Vec<String> {
    let mut opts: Vec<String> = Vec::new();

    // Profile cflags (-O…, -g…, -fsanitize=…, [profile.<kind>]
    // extra-cflags). Same order build::build_cflags emits.
    opts.extend(profile.cflags());

    // [clang] extra-cflags.
    opts.extend(manifest.clang.extra_cflags.iter().cloned());

    // -fvisibility=hidden: same default the v0.3 prelude pinned.
    opts.push("-fvisibility=hidden".to_string());

    // -include <prelude>: two separate argv tokens (clang
    // requires them split). CMake preserves list order; no
    // SHELL: prefix needed because -include doesn't collide
    // with any other flag CMake adds.
    opts.push("-include".to_string());
    opts.push(prelude.display().to_string());

    if let Some(plugin) = plugin {
        // Plugin loader. SHELL: prefix prevents CMake from
        // splitting / re-ordering this around other -f flags
        // (V42D-5). Path is absolute, resolved by
        // plugin::discover() before collect_view ran.
        opts.push(format!("SHELL:-fplugin={}", plugin.path.display()));
    }

    // Always suppress `-Wunknown-attributes` so cust-attribute
    // decls don't drown the build in warnings even when the
    // plugin is loaded (V42D-5 defensive).
    opts.push("-Wno-unknown-attributes".to_string());

    opts
}

const fn map_kind(k: &CrateKind) -> MemberKind {
    match k {
        CrateKind::Lib { .. } => MemberKind::LibOnly,
        CrateKind::Bin { .. } => MemberKind::BinOnly,
        CrateKind::LibAndBin { .. } => MemberKind::LibAndBin,
    }
}

fn collect_sources(
    crate_root: &Path,
    entry_source: &Path,
    crate_name: &str,
    rewrite_root: &Path,
    layout: &TargetLayout,
) -> Result<Vec<SourceFile>> {
    let modules = modules::discover(crate_root, entry_source)
        .with_context(|| format!("discovering module graph for `{crate_name}`"))?;
    let mut out: Vec<SourceFile> = Vec::with_capacity(modules.len());
    for m in &modules {
        // Post-rewrite path: target/<profile>/.rewrite/<crate>/<rel>.
        // <rel> is the source's path relative to the crate root,
        // preserving src/<…>.c structure (V42D scope item shape +
        // design doc "Headline outcome" example).
        let rel = m
            .source_path
            .strip_prefix(crate_root)
            .unwrap_or(&m.source_path);
        let rewrite_path = rewrite_root.join(crate_name).join(rel);

        // OBJECT_DEPENDS: every `#cust use crate::<importee>`
        // edge resolves to the importee's fragment header.
        // V42D-4 wants topological order; slice A uses source-
        // declaration order from the scanner (matches topo in
        // practice for non-cyclic graphs, which V40D-11 already
        // requires for fragment convergence).
        let object_depends = m
            .imports
            .iter()
            .map(|importee| layout.fragment_path(crate_name, importee))
            .collect();

        out.push(SourceFile {
            path: rewrite_path,
            object_depends,
        });
    }
    Ok(out)
}

/// Write the workspace's `CMakeLists` into the build tree
/// (V42D-13 path + V42D-8 configure-skip stamp).
///
/// Slice A's standalone emit entry point; slice B's
/// `emit_and_drive_cmake` is now the production caller, so this
/// stays around mainly for tests and out-of-band tooling.
#[allow(dead_code)] // superseded as a build-path callee by `emit_and_drive_cmake`; kept for tests
pub fn emit_workspace_cmakelists(
    ws: &Workspace,
    profile_kind: ProfileKind,
    plugin: Option<&Plugin>,
) -> Result<WriteOutcome> {
    let view = collect_view(ws, profile_kind, plugin)?;
    let bytes = generate(&view).into_bytes();
    let layout = TargetLayout::for_workspace(&ws.root, profile_kind);
    let cmake_dir = layout.profile_root.join("cmake");
    let cmakelists = cmake_dir.join("CMakeLists.txt");
    let stamp = cmake_dir.join("stamp").join("cmakelists.sha256");
    write_if_changed(&cmakelists, &bytes, &stamp, view.plugin_path.as_deref())
}

// ─── Slice B: drive cmake + ninja ───────────────────────────────

/// Inputs to `emit_and_drive_cmake`. Mirror of the v0.4.2 design
/// doc's `cust build` / `cust build -p <name>` shape.
#[derive(Default)]
pub struct DriveOptions<'a> {
    /// `Some(name)` lowers to `cmake --build --target <name>`.
    /// `None` builds every default target. Slice B accepts a
    /// single member name; v0.4.4 multi-bin will generalise to a
    /// `Vec<String>`.
    pub only: Option<&'a str>,
    /// `cmake --build -j <jobs>`. `None` lets `Ninja` pick (`Ninja`
    /// defaults to `nproc`). Slice D will plumb `--jobs` / env
    /// vars through here.
    pub jobs: Option<u32>,
    /// V42D-14: when `true`, the build step picks the
    /// `<member>__test` targets instead of the default lib +
    /// bin ones (which are `EXCLUDE_FROM_ALL` for test targets).
    /// The emitted `CMakeLists` is identical either way, so
    /// flipping modes neither churns the V42D-8 stamp nor
    /// triggers a `CMake` reconfigure.
    pub test_build: bool,
}

/// One-shot orchestrator for the v0.4.2 `CMake`-driven build path.
/// Emits the workspace `CMakeLists`, optionally reconfigures, and
/// drives `cmake --build`. Returns once `Ninja` exits.
///
/// Steps (per V42D-16):
///
/// 1. `find_cmake()` / `find_ninja()` — install hints on miss.
/// 2. `collect_view` → `generate` → `write_if_changed`.
/// 3. Configure: if `WriteOutcome::Wrote` *or* the build dir
///    doesn't already contain a `CMakeCache.txt`, run
///    `cmake -G `Ninja` -S <cmake_dir> -B <build_dir>
///    -DCMAKE_C_COMPILER=<abs/clang>`. Otherwise skip (V42D-8:
///    stamp matched, nothing to reconfigure).
/// 4. Build: `cmake --build <build_dir>` (with `--target <name>`
///    when `opts.only` is set; with `-j <jobs>` when set).
/// 5. Publish `compile_commands.json` (V42D-12): symlink
///    `target/<profile>/compile_commands.json` and the legacy
///    `target/compile_commands.json` to the `CMake`-emitted
///    `<build_dir>/compile_commands.json`.
///
/// Both cmake and ninja get their stdout + stderr piped through
/// `diag_rewrite::rewrite` (V42D-18).
pub fn emit_and_drive_cmake(
    ws: &Workspace,
    profile_kind: ProfileKind,
    clang: &crate::clang::Clang,
    plugin: Option<&Plugin>,
    opts: &DriveOptions<'_>,
) -> Result<()> {
    let cmake = find_cmake()?;
    let _ninja = find_ninja()?; // discovery + version-parse check; CMake invokes ninja itself

    let layout = TargetLayout::for_workspace(&ws.root, profile_kind);
    let cmake_dir = layout.profile_root.join("cmake");
    let build_dir = cmake_dir.join("build");
    let cmakelists = cmake_dir.join("CMakeLists.txt");
    let stamp = cmake_dir.join("stamp").join("cmakelists.sha256");

    let view = collect_view(ws, profile_kind, plugin)?;
    let bytes = generate(&view).into_bytes();
    let outcome = write_if_changed(&cmakelists, &bytes, &stamp, view.plugin_path.as_deref())?;

    // V42D-14: ensure every member's `cust_test_main_<crate>.c`
    // runner TU exists on disk before configure. CMake validates
    // every `add_executable` source path at configure time even
    // when the target is `EXCLUDE_FROM_ALL`, so a missing runner
    // TU during `cust build` would fail configure. The build
    // path doesn't need real runner content (the target is
    // never built); a tiny stub is enough. `cust test` calls
    // `build::write_test_runner_tu` to overwrite the stub with
    // the real concatenation before reaching the build step.
    ensure_runner_tu_stubs(&view, &cmake_dir)?;

    // Configure if the CMakeLists was just written OR there's no
    // existing CMake cache to reuse. Either condition forces a
    // fresh `cmake -G Ninja` run. Mode flips between `cust
    // build` and `cust test` are NOT a reason to reconfigure:
    // the same CMakeLists drives both — test targets are
    // `EXCLUDE_FROM_ALL` and selected per-invocation via
    // `cmake --build --target` below.
    let must_configure =
        outcome == WriteOutcome::Wrote || !build_dir.join("CMakeCache.txt").is_file();
    if must_configure {
        fs::create_dir_all(&build_dir)
            .with_context(|| format!("creating `{}`", build_dir.display()))?;
        // Wipe any stale cache so a compiler-path change (or any
        // other -D the driver might add later) takes effect on the
        // next project() call. Object files under CMakeFiles/ stay.
        let _ = fs::remove_file(build_dir.join("CMakeCache.txt"));
        let mut cmd = Command::new(&cmake.path);
        cmd.arg("-G").arg("Ninja");
        cmd.arg("-S").arg(&cmake_dir);
        cmd.arg("-B").arg(&build_dir);
        // V42D-3 / Headline outcome: cust drives clang, not the
        // system default. Passing on the configure line means
        // CMake records it in CMakeCache.txt and uses it for
        // every subsequent `cmake --build`.
        cmd.arg(format!("-DCMAKE_C_COMPILER={}", clang.path.display()));
        run_streaming(cmd, "cmake configure")?;
    }

    // Build.
    let mut cmd = Command::new(&cmake.path);
    cmd.arg("--build").arg(&build_dir);
    if let Some(target) = opts.only {
        // For lib+bin members the bin lives at a `-bin`-suffixed
        // CMake target name; the lib keeps the unsuffixed
        // member name. `-p <name>` builds both halves — or, in
        // test mode, just the `<name>__test` target.
        for cmake_target in target_names_for(&view, target, opts.test_build) {
            cmd.arg("--target").arg(cmake_target);
        }
    } else if opts.test_build {
        // No `-p`: in test mode build only the `__test` targets,
        // not the lib + bin defaults. Mirrors Cargo's `cargo
        // test` which doesn't link production bins.
        for m in &view.members {
            if let Some(t) = &m.test_target {
                cmd.arg("--target").arg(&t.target_name);
            }
        }
    }
    if let Some(jobs) = opts.jobs {
        cmd.arg("-j").arg(jobs.to_string());
    }
    run_streaming(cmd, "cmake --build")?;

    publish_compile_commands(&layout, &build_dir)?;
    Ok(())
}

/// `CMake` target name(s) for a member, used when lowering
/// `cust build -p <name>` to `cmake --build --target ...`.
/// Returns `[lib]`, `[bin]`, or `[lib, bin]` for build mode;
/// `[<name>__test]` for test mode (V42D-14). Unknown member
/// names produce an empty Vec (the caller fails at the
/// workspace-membership check before reaching this).
fn target_names_for<'a>(
    view: &'a WorkspaceView,
    member_name: &str,
    test_mode: bool,
) -> Vec<&'a str> {
    let Some(m) = view.members.iter().find(|m| m.name == member_name) else {
        return Vec::new();
    };
    if test_mode {
        return m
            .test_target
            .as_ref()
            .map(|t| vec![t.target_name.as_str()])
            .unwrap_or_default();
    }
    let mut out = Vec::with_capacity(2);
    if m.kind.has_lib() {
        out.push(m.name.as_str());
    }
    if m.kind.has_bin() {
        out.push(m.bin_target_name.as_str());
    }
    out
}

/// V42D-14: ensure each member's `cust_test_main_<crate>.c`
/// runner TU exists on disk before `CMake` configure runs.
/// `CMake` validates every `add_executable` source path at
/// configure time even for `EXCLUDE_FROM_ALL` targets, so a
/// missing runner TU would fail configure during `cust build`.
///
/// On the test path `build::write_test_runner_tu` overwrites the
/// stub with the real runner before reaching the build step;
/// the stub itself is never compiled (the test target only
/// reaches the `Ninja` graph when `cust test` selects it via
/// `cmake --build --target <crate>__test`).
///
/// Idempotent + cheap: stubs are only written when the runner
/// TU file is missing, and the stub content is small enough
/// that any subsequent `write_if_byte_different` from the test
/// path always replaces it.
fn ensure_runner_tu_stubs(view: &WorkspaceView, cmake_dir: &Path) -> Result<()> {
    const STUB: &[u8] = b"/* @generated by cust \xe2\x80\x94 build-mode stub.\n\
 * The real runner is concatenated by `cust test`'s\n\
 * build::write_test_runner_tu before this target is built;\n\
 * see cust/src/test_runner.rs.\n\
 */\n";
    for m in &view.members {
        let Some(t) = &m.test_target else { continue };
        // The runner TU is the only source under `cmake_dir/`
        // (the lib sources all live under `.rewrite/<crate>/`).
        for src in &t.sources {
            if src.path.starts_with(cmake_dir) && !src.path.is_file() {
                if let Some(parent) = src.path.parent() {
                    fs::create_dir_all(parent)
                        .with_context(|| format!("creating `{}`", parent.display()))?;
                }
                fs::write(&src.path, STUB)
                    .with_context(|| format!("writing runner stub `{}`", src.path.display()))?;
            }
        }
    }
    Ok(())
}

/// Publish `CMake`'s `compile_commands.json` at both the canonical
/// V42D-12 location (`target/<profile>/compile_commands.json`)
/// and the legacy v0.1 location (`target/compile_commands.json`)
/// via symlinks. The legacy location stays during v0.4.x because
/// existing dev tooling and the v0.1+ test suite reach for it.
fn publish_compile_commands(layout: &TargetLayout, build_dir: &Path) -> Result<()> {
    let canonical = build_dir.join("compile_commands.json");
    if !canonical.is_file() {
        return Ok(()); // configure was skipped and an old cache lacks the export — non-fatal
    }
    let v42d12_path = layout.profile_root.join("compile_commands.json");
    let legacy_path = layout.target_root.join("compile_commands.json");
    symlink_overwrite(&canonical, &v42d12_path)?;
    symlink_overwrite(&canonical, &legacy_path)?;
    Ok(())
}

fn symlink_overwrite(target: &Path, link: &Path) -> Result<()> {
    if let Some(parent) = link.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
    }
    if fs::symlink_metadata(link).is_ok() {
        fs::remove_file(link).with_context(|| format!("removing stale `{}`", link.display()))?;
    }
    #[cfg(unix)]
    std::os::unix::fs::symlink(target, link)
        .with_context(|| format!("symlinking `{}` -> `{}`", link.display(), target.display()))?;
    #[cfg(not(unix))]
    fs::copy(target, link)
        .map(|_| ())
        .with_context(|| format!("copying `{}` -> `{}`", target.display(), link.display()))?;
    Ok(())
}

// ─── Subprocess wrapper + diagnostic rewrite ────────────────────
//
// Inline helper per V42D-18 (the design says "promote to a shared
// module only if a second caller appears"). Spawns `cmd` with
// piped stdout + stderr; one reader thread per pipe pushes each
// line through `diag_rewrite::rewrite` before printing to the
// driver's own stdout / stderr.

fn run_streaming(mut cmd: Command, ctx: &'static str) -> Result<()> {
    use std::io::{BufRead, BufReader};

    cmd.stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    let mut child = cmd.spawn().with_context(|| format!("spawning {ctx}"))?;

    let stdout = child.stdout.take().expect("piped stdout");
    let stderr = child.stderr.take().expect("piped stderr");

    let h_out = std::thread::spawn(move || {
        let reader = BufReader::new(stdout);
        for line in reader.lines().map_while(Result::ok) {
            let rewritten = crate::diag_rewrite::rewrite(&line);
            println!("{rewritten}");
        }
    });
    let h_err = std::thread::spawn(move || {
        let reader = BufReader::new(stderr);
        for line in reader.lines().map_while(Result::ok) {
            let rewritten = crate::diag_rewrite::rewrite(&line);
            eprintln!("{rewritten}");
        }
    });

    let status = child.wait().with_context(|| format!("waiting on {ctx}"))?;
    // Joining the reader threads is fire-and-forget: the pipes
    // closed when the child exited, so the threads finish on
    // their own; we just sync before returning so the driver
    // doesn't print its own "Finished" line before the child's
    // last lines flush.
    let _ = h_out.join();
    let _ = h_err.join();

    if !status.success() {
        bail!("{ctx} failed with status {status}");
    }
    Ok(())
}

#[cfg(test)]
mod tests;
