//! `CMakeLists` emission for the v0.4.2 CMake-driven build backend
//! (`docs/design/v0.4.2.md`).
//!
//! Slice A scope (V42D-16): this module owns three concerns and
//! nothing else.
//!
//! 1. **Emitter** — pure function `generate(&WorkspaceView) ->
//!    String`. Produces deterministic CMakeLists.txt bytes for
//!    the whole workspace per V42D-13 (one file, all members) and
//!    V42D-4 (byte-stable on no-input-change). Golden-file tested
//!    in `cmake_emit::tests`.
//!
//! 2. **Configure-skip stamp** — `compute_stamp` hashes the
//!    `CMakeLists` bytes **concatenated with the plugin .so bytes**
//!    per V42D-8 + RQ-V42-1. `write_if_changed` atomically writes
//!    the `CMakeLists` into place and updates the stamp only when
//!    the hash differs.
//!
//! 3. **Tool discovery** — `find_cmake` / `find_ninja` per
//!    V42D-10 / V42D-11. `cmake` is gated at the 3.21 floor;
//!    `ninja` has no version floor.
//!
//! In slice A this module is **wired but not load-bearing**:
//! `build_workspace` calls `write_if_changed` as a side effect so
//! the `CMakeLists` shows up on disk, but `compile_one_module` is
//! still what drives phase 2 — nothing reads the file or invokes
//! `cmake`. Slice B (V42D-16) replaces `compile_one_module` /
//! `compile_tree` with an `emit_and_drive_cmake()` that wires
//! this module to `Command::new(cmake)`.

use std::{
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use anyhow::{bail, Context, Result};
use sha2::{Digest, Sha256};

// ─── Emitter input model ────────────────────────────────────────

/// Whole-workspace view the emitter consumes. Owned (not borrowed
/// against the live `Workspace`) so unit tests can fabricate
/// inputs without standing up a manifest tree.
#[derive(Debug, Clone)]
pub struct WorkspaceView {
    /// cust version string baked into the `@generated by` header
    /// comment. V42D-4: version is part of the byte format and
    /// therefore part of the configure-skip stamp; a cust upgrade
    /// that changes this string churns the stamp on purpose.
    pub cust_version: String,
    /// `CMAKE_C_STANDARD` value, e.g. `"23"`. v0.4.2 hard-codes
    /// to 23 in practice (matches clang ≥ 19 default for cwork);
    /// surfaced as a field so slice B can plumb `[clang] std` /
    /// per-member overrides through later.
    pub c_standard: String,
    /// Absolute path to the cust clang plugin .so, resolved by
    /// `plugin::Plugin::discover()`. `None` is permitted in
    /// slice A so the write-side-effect from `build_workspace`
    /// remains a no-op when the plugin is missing (slice B will
    /// turn this into a hard error at `build_workspace` time —
    /// the emitter itself stays permissive).
    pub plugin_path: Option<PathBuf>,
    /// Members in topological (build) order: dependencies before
    /// consumers. V42D-4 + same rule the existing
    /// `Workspace::build_order` applies.
    pub members: Vec<MemberView>,
}

/// One workspace member. Slice A emits at most two `CMake` targets
/// per member: one library + one executable. Multi-bin (v0.4.4)
/// will extend `bin_sources` from `Vec<SourceFile>` to a list of
/// `(target_name, sources)` tuples; not in slice A scope.
#[derive(Debug, Clone)]
pub struct MemberView {
    /// `[package].name`. Used verbatim as the `CMake` target name.
    pub name: String,
    /// What the member produces. `LibOnly` / `BinOnly` /
    /// `LibAndBin`. Mirrors `manifest::CrateKind` but stays
    /// CrateKind-free at the emitter boundary so tests don't
    /// have to construct a full `Manifest`.
    pub kind: MemberKind,
    /// Lib-half sources in topological order over `#cust use
    /// crate::<mod>` edges (= the `<crate>.h` concatenation
    /// order; V42D-4). Empty when `kind` is `BinOnly`.
    pub lib_sources: Vec<SourceFile>,
    /// Bin-half sources in the same topological order. Empty
    /// when `kind` is `LibOnly`.
    pub bin_sources: Vec<SourceFile>,
    /// Absolute path the lib archive is placed in via
    /// `ARCHIVE_OUTPUT_DIRECTORY`. Preserves the
    /// `target/<profile>/build/<crate>/` layout from v0.3+
    /// (V42D-13 keeps per-crate driver outputs at their old
    /// paths even though the `CMake` tree is workspace-level).
    pub archive_output_dir: PathBuf,
    /// Include dirs the bin half needs to reach. For a
    /// lib+bin member this is the crate's own lib include dir
    /// (so `main.c` can `#include "<crate>.h"`). For pure-bin
    /// members it's typically the per-crate `build/<crate>/include/`
    /// of each workspace dep (publish-via-symlink dep view from
    /// v0.3 still works as include resolution).
    ///
    /// Order is preserved verbatim; the caller is responsible
    /// for determinism (V42D-4: callers pass topo-ordered lists).
    pub bin_include_dirs: Vec<PathBuf>,
    /// Names of other workspace members this member's bin half
    /// links against, in topological order. Lowered to
    /// `target_link_libraries(<bin> PRIVATE <dep>)` per V42D-13.
    /// Empty for lib-only members.
    pub workspace_link_deps: Vec<String>,
}

/// Mirror of `manifest::CrateKind`, exposed at the emitter
/// boundary so unit tests can construct inputs without dragging
/// the whole manifest module in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemberKind {
    LibOnly,
    BinOnly,
    LibAndBin,
}

impl MemberKind {
    const fn has_lib(self) -> bool {
        matches!(self, Self::LibOnly | Self::LibAndBin)
    }
    const fn has_bin(self) -> bool {
        matches!(self, Self::BinOnly | Self::LibAndBin)
    }
}

/// One source file passed to `CMake`. Path is absolute; the emitter
/// quotes it directly (no `${CMAKE_CURRENT_LIST_DIR}` rewriting —
/// the caller has already resolved everything).
#[derive(Debug, Clone)]
pub struct SourceFile {
    /// Absolute path to the post-`#cust use`-rewrite source file
    /// (`target/<profile>/.rewrite/<crate>/<…>.c` once slice B
    /// moves the rewrite output there; today's preprocessed
    /// path works equally well at slice A since the emitter
    /// isn't load-bearing).
    pub path: PathBuf,
    /// Absolute paths to fragment headers this TU imports via
    /// `#cust use crate::<importee>`, in topological order over
    /// the dep edges (V42D-4 + V42D-6). Empty for TUs with no
    /// cross-module imports. Lowered to a `CMake`
    /// `set_source_files_properties(... OBJECT_DEPENDS ...)`
    /// block per V42D-6.
    pub object_depends: Vec<PathBuf>,
}

// ─── Emitter ────────────────────────────────────────────────────

/// Render the workspace `CMakeLists` for `view`. Pure function;
/// determinism is the caller's responsibility (the emitter
/// preserves the orders it's handed).
///
/// Output shape pinned by the golden file at
/// `src/cmake_emit/testdata/cwork.cmake` (V42D-4).
#[must_use]
pub fn generate(view: &WorkspaceView) -> String {
    let mut out = String::new();

    // Header (V42D-4: cust version in `@generated`, no timestamp).
    let _ = writeln!(
        out,
        "# @generated by cust v{} — DO NOT EDIT",
        view.cust_version,
    );
    out.push_str("# Regenerated every `cust build`. Edits are lost.\n");
    out.push_str("cmake_minimum_required(VERSION 3.21)\n");
    out.push_str("project(cust_workspace LANGUAGES C)\n");
    out.push('\n');
    let _ = writeln!(out, "set(CMAKE_C_STANDARD {})", view.c_standard);
    out.push_str("set(CMAKE_C_STANDARD_REQUIRED ON)\n");
    out.push_str("set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n");

    // Per-member blocks.
    for m in &view.members {
        if m.kind.has_lib() {
            emit_library(&mut out, m);
        }
        if m.kind.has_bin() {
            emit_executable(&mut out, m);
        }
    }

    // Shared compile options foreach (V42D-5). Skipped entirely
    // when no plugin was discovered — slice A keeps the
    // emitter permissive; slice B will reject `plugin_path =
    // None` at `build_workspace` time.
    if let Some(plugin) = view.plugin_path.as_deref() {
        emit_shared_compile_options(&mut out, view, plugin);
    }

    out
}

fn emit_library(out: &mut String, m: &MemberView) {
    out.push('\n');
    let _ = writeln!(out, "# ---- crate: {} (library) ----", m.name);
    let _ = writeln!(out, "add_library({} STATIC", m.name);
    for src in &m.lib_sources {
        let _ = writeln!(out, "    \"{}\"", src.path.display());
    }
    out.push_str(")\n");
    let _ = writeln!(out, "set_target_properties({} PROPERTIES", m.name);
    let _ = writeln!(
        out,
        "    ARCHIVE_OUTPUT_DIRECTORY \"{}\"",
        m.archive_output_dir.display(),
    );
    let _ = writeln!(out, "    OUTPUT_NAME {}", m.name);
    out.push_str(")\n");
    emit_object_depends(out, &m.lib_sources);
}

fn emit_executable(out: &mut String, m: &MemberView) {
    out.push('\n');
    let _ = writeln!(out, "# ---- crate: {} (binary) ----", m.name);
    let _ = writeln!(out, "add_executable({}", m.name);
    for src in &m.bin_sources {
        let _ = writeln!(out, "    \"{}\"", src.path.display());
    }
    out.push_str(")\n");
    emit_object_depends(out, &m.bin_sources);
    if !m.bin_include_dirs.is_empty() {
        let _ = writeln!(out, "target_include_directories({} PRIVATE", m.name);
        for dir in &m.bin_include_dirs {
            let _ = writeln!(out, "    \"{}\"", dir.display());
        }
        out.push_str(")\n");
    }
    if !m.workspace_link_deps.is_empty() {
        let _ = writeln!(out, "target_link_libraries({} PRIVATE", m.name);
        for dep in &m.workspace_link_deps {
            let _ = writeln!(out, "    {dep}");
        }
        out.push_str(")\n");
    }
}

/// Emit a `set_source_files_properties(... OBJECT_DEPENDS ...)`
/// block for every source with non-empty `object_depends`
/// (V42D-6). One block per source, semicolon-joined fragment
/// list. Sources with empty deps emit nothing.
fn emit_object_depends(out: &mut String, sources: &[SourceFile]) {
    for src in sources {
        if src.object_depends.is_empty() {
            continue;
        }
        out.push_str("set_source_files_properties(\n");
        let _ = writeln!(out, "    \"{}\"", src.path.display());
        out.push_str("    PROPERTIES OBJECT_DEPENDS\n    \"");
        for (i, dep) in src.object_depends.iter().enumerate() {
            if i > 0 {
                out.push(';');
            }
            let _ = write!(out, "{}", dep.display());
        }
        out.push_str("\"\n)\n");
    }
}

fn emit_shared_compile_options(out: &mut String, view: &WorkspaceView, plugin: &Path) {
    out.push('\n');
    out.push_str("# ---- shared compile options ----\n");
    out.push_str("# Plugin invocation — absolute path baked at emit-time (V42D-5).\n");
    out.push_str("foreach(_t");
    for m in &view.members {
        if m.kind.has_lib() {
            let _ = write!(out, " {}", m.name);
        }
        if m.kind.has_bin() {
            let _ = write!(out, " {}", m.name);
        }
    }
    out.push_str(")\n");
    out.push_str("    target_compile_options(${_t} PRIVATE\n");
    let _ = writeln!(out, "        \"SHELL:-fplugin={}\"", plugin.display());
    out.push_str("        -Wno-unknown-attributes\n");
    out.push_str("    )\n");
    out.push_str("endforeach()\n");
}

// ─── Configure-skip stamp (V42D-8 + RQ-V42-1) ───────────────────

/// 32-byte SHA-256. Newtype so calling code can't mix it up with
/// arbitrary byte buffers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Stamp([u8; 32]);

impl Stamp {
    /// Lowercase hex representation, suitable for writing into
    /// the stamp file.
    #[must_use]
    pub fn to_hex(self) -> String {
        let mut out = String::with_capacity(64);
        for b in self.0 {
            let _ = write!(out, "{b:02x}");
        }
        out
    }

    /// Parse a 64-char lowercase hex string. Returns `None` on
    /// any malformed input (wrong length, non-hex character, etc.)
    /// — callers treat that the same as a missing stamp file:
    /// stamp mismatch ⇒ force reconfigure.
    #[must_use]
    #[allow(dead_code)] // consumed by tests; slice B reads the stamp at configure time
    pub fn from_hex(s: &str) -> Option<Self> {
        if s.len() != 64 {
            return None;
        }
        let mut bytes = [0u8; 32];
        for (i, b) in bytes.iter_mut().enumerate() {
            let hi = hex_nibble(s.as_bytes()[i * 2])?;
            let lo = hex_nibble(s.as_bytes()[i * 2 + 1])?;
            *b = (hi << 4) | lo;
        }
        Some(Self(bytes))
    }
}

const fn hex_nibble(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        _ => None,
    }
}

/// SHA-256 of `cmakelists_bytes` concatenated with the bytes of
/// the file at `plugin_path` (V42D-8 + RQ-V42-1). The plugin's
/// path is already part of the `CMakeLists` (V42D-5 bakes it), so
/// a path change already churns the stamp via `cmakelists_bytes`;
/// hashing the plugin's *contents* closes the same-path-different-
/// .so gap that path-only hashing misses.
///
/// `plugin_path = None` (slice A no-plugin case) omits the plugin
/// chunk entirely. This is consistent: when there's no plugin in
/// the `CMakeLists`, there's no plugin contribution to hash either.
pub fn compute_stamp(cmakelists_bytes: &[u8], plugin_path: Option<&Path>) -> Result<Stamp> {
    let mut hasher = Sha256::new();
    hasher.update(cmakelists_bytes);
    if let Some(path) = plugin_path {
        let plugin_bytes = fs::read(path)
            .with_context(|| format!("reading plugin `{}` for stamp", path.display()))?;
        hasher.update(&plugin_bytes);
    }
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest);
    Ok(Stamp(out))
}

/// Result of `write_if_changed`. Slice A doesn't act on the
/// variant (the write is purely a side effect); slice B will
/// branch on it to decide whether to skip `cmake -G Ninja`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WriteOutcome {
    /// `CMakeLists` + stamp were already up to date; nothing
    /// touched on disk. Slice B uses this to skip the configure
    /// step (V42D-8).
    Unchanged,
    /// `CMakeLists` was (re)written and the stamp updated. Slice
    /// B uses this to require a `cmake -G Ninja` run.
    Wrote,
}

/// Atomically write `cmakelists_bytes` to `cmakelists_path` and
/// the new stamp to `stamp_path` iff the recomputed stamp
/// differs from the on-disk stamp (V42D-8).
///
/// Creates parent directories as needed. The `CMakeLists` and the
/// stamp are both written via `<path>.tmp` + `rename` so a crash
/// mid-write doesn't leave a desynced pair on disk.
pub fn write_if_changed(
    cmakelists_path: &Path,
    cmakelists_bytes: &[u8],
    stamp_path: &Path,
    plugin_path: Option<&Path>,
) -> Result<WriteOutcome> {
    let new_stamp = compute_stamp(cmakelists_bytes, plugin_path)?;

    // Read existing stamp; treat any read/parse failure as
    // "stamp absent → must reconfigure" (matches the design's
    // permissive shape — we never refuse to build because the
    // stamp file is corrupt).
    let existing = fs::read_to_string(stamp_path)
        .ok()
        .and_then(|s| Stamp::from_hex(s.trim()));

    if existing == Some(new_stamp) && cmakelists_path.is_file() {
        return Ok(WriteOutcome::Unchanged);
    }

    if let Some(parent) = cmakelists_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
    }
    if let Some(parent) = stamp_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating `{}`", parent.display()))?;
    }

    write_atomically(cmakelists_path, cmakelists_bytes)?;
    write_atomically(stamp_path, new_stamp.to_hex().as_bytes())?;
    Ok(WriteOutcome::Wrote)
}

fn write_atomically(path: &Path, bytes: &[u8]) -> Result<()> {
    let tmp = path.with_extension({
        let mut ext = path
            .extension()
            .map(|e| e.to_string_lossy().into_owned())
            .unwrap_or_default();
        if !ext.is_empty() {
            ext.push('.');
        }
        ext.push_str("tmp");
        ext
    });
    fs::write(&tmp, bytes).with_context(|| format!("writing `{}`", tmp.display()))?;
    fs::rename(&tmp, path)
        .with_context(|| format!("renaming `{}` to `{}`", tmp.display(), path.display()))?;
    Ok(())
}

// ─── Tool discovery (V42D-10 / V42D-11) ─────────────────────────
//
// Slice A defines + tests the discovery surface. Slice B
// (V42D-16's `emit_and_drive_cmake`) is the first caller. The
// `#[allow(dead_code)]` blocks below mark the surface as
// intentionally-unused-until-slice-B; they go away when slice B
// lands.

/// Resolved external tool — absolute path + parsed `--version`.
#[derive(Debug, Clone)]
#[allow(dead_code)] // consumed by slice B
pub struct Tool {
    /// Absolute path the PATH lookup resolved to.
    pub path: PathBuf,
    /// `(major, minor, patch)`. Patch is 0 when the `--version`
    /// output omits it (some Ninja builds report `1.11`).
    pub version: (u32, u32, u32),
}

/// Minimum `CMake` version per V42D-9.
#[allow(dead_code)] // consumed by slice B via find_cmake
const CMAKE_MIN: (u32, u32, u32) = (3, 21, 0);

/// Look up `cmake` on `$PATH`, run `cmake --version`, parse the
/// first line, enforce the 3.21 floor (V42D-9 / V42D-10).
///
/// In slice A this is **defined and tested but not called from
/// the build path** — slice B's `emit_and_drive_cmake()` is the
/// first consumer. Surfaced now so the discovery surface is in
/// place when slice B lands.
#[allow(dead_code)] // consumed by slice B
pub fn find_cmake() -> Result<Tool> {
    let tool = find_tool("cmake", CMAKE_INSTALL_HINT)?;
    if tool.version < CMAKE_MIN {
        bail!(
            "found `cmake` at `{}` reporting version {}.{}.{}, but cust v0.4.2+ \
             requires cmake >= {}.{}.{}\n{}",
            tool.path.display(),
            tool.version.0,
            tool.version.1,
            tool.version.2,
            CMAKE_MIN.0,
            CMAKE_MIN.1,
            CMAKE_MIN.2,
            CMAKE_INSTALL_HINT,
        );
    }
    Ok(tool)
}

/// Look up `ninja` on `$PATH`, run `ninja --version`, parse it.
/// No version floor (V42D-11 — Ninja's build-format compat is
/// excellent). Surfaced now (slice B will be the first caller).
#[allow(dead_code)] // consumed by slice B
pub fn find_ninja() -> Result<Tool> {
    find_tool("ninja", NINJA_INSTALL_HINT)
}

const CMAKE_INSTALL_HINT: &str = "\
  hint: cust v0.4.2+ requires cmake >= 3.21 as a build-time dependency
        Linux:   apt install cmake     (or your distro's equivalent)
        macOS:   brew install cmake
        Windows: install from https://cmake.org/download/
  note: see docs/design/v0.4.2.md for the rationale";

const NINJA_INSTALL_HINT: &str = "\
  hint: cust v0.4.2+ requires ninja as a build-time dependency
        Linux:   apt install ninja-build
        macOS:   brew install ninja
        Windows: install from https://ninja-build.org/
  note: see docs/design/v0.4.2.md for the rationale";

#[allow(dead_code)] // consumed by slice B via find_cmake / find_ninja
fn find_tool(tool: &str, install_hint: &str) -> Result<Tool> {
    let output = Command::new(tool)
        .arg("--version")
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output();
    let output = match output {
        Ok(o) => o,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            bail!("error: `{tool}` not found on PATH\n{install_hint}")
        }
        Err(e) => return Err(e).with_context(|| format!("invoking `{tool} --version`")),
    };
    if !output.status.success() {
        bail!("`{tool} --version` exited with status {}", output.status);
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let first_line = stdout.lines().next().unwrap_or("");
    let version = parse_version(first_line)
        .with_context(|| format!("parsing `{tool} --version` first line: `{first_line}`"))?;
    // PATH lookup completed via Command::new, but we don't get
    // the absolute path back directly. Re-resolve via `which`-
    // equivalent: spawn `command -v <tool>` is shell-specific;
    // simpler: just record the bare tool name and let downstream
    // `Command::new(&tool.path)` re-resolve. Same posture as the
    // existing `clang::Clang::path` field.
    Ok(Tool {
        path: PathBuf::from(tool),
        version,
    })
}

/// Parse a `<tool> --version` first line. Looks for the first
/// `MAJOR.MINOR[.PATCH]` sequence and returns it. `CMake`'s first
/// line is `cmake version 3.28.1`; Ninja's is just `1.11.1`.
#[allow(dead_code)] // consumed by slice B via find_tool
fn parse_version(line: &str) -> Result<(u32, u32, u32)> {
    let mut chars = line.char_indices().peekable();
    while let Some(&(start, c)) = chars.peek() {
        if c.is_ascii_digit() {
            // Walk while [0-9.] keeps making sense.
            let mut end = start;
            for (i, ch) in line[start..].char_indices() {
                if ch.is_ascii_digit() || ch == '.' {
                    end = start + i + ch.len_utf8();
                } else {
                    break;
                }
            }
            let candidate = &line[start..end];
            if let Some(v) = try_triple(candidate) {
                return Ok(v);
            }
            // Skip this run and keep looking.
            chars.nth(end - start - 1);
            continue;
        }
        chars.next();
    }
    bail!("no MAJOR.MINOR[.PATCH] found in `{line}`")
}

#[allow(dead_code)] // consumed by slice B via parse_version
fn try_triple(s: &str) -> Option<(u32, u32, u32)> {
    let mut parts = s.split('.').map(str::parse::<u32>);
    let major = parts.next()?.ok()?;
    let minor = parts.next()?.ok()?;
    let patch = parts.next().and_then(Result::ok).unwrap_or(0);
    Some((major, minor, patch))
}

// ─── Workspace → WorkspaceView bridge (slice A wire-up) ─────────

use crate::{
    manifest::CrateKind, modules, plugin::Plugin, profile::ProfileKind,
    target_layout::TargetLayout, workspace::Workspace,
};

/// Walk `ws` and produce a `WorkspaceView` describing every
/// member's lib/bin shape, sources (post-`#cust use` rewrite
/// paths), and `OBJECT_DEPENDS` fragment edges.
///
/// Slice A only: this duplicates the module walk
/// `compile_tree` does. Slice B (V42D-16) will fuse them so the
/// driver walks once per build, not twice. The duplicate cost is
/// tolerable today because slice A doesn't yet drive `cmake` —
/// the walk's only consumer is the configure-skip stamp.
///
/// The view always contains every workspace member, regardless of
/// `cust build -p <name>` scoping (V42D-13: one `CMakeLists` for
/// the whole workspace; `-p` lowers at `cmake --build --target`
/// time, not at emit time). This keeps the stamp stable across
/// `-p` variations.
pub fn collect_view(
    ws: &Workspace,
    profile_kind: ProfileKind,
    plugin: Option<&Plugin>,
) -> Result<WorkspaceView> {
    let layout = TargetLayout::for_workspace(&ws.root, profile_kind);
    let rewrite_root = layout.profile_root.join(".rewrite");

    let mut members: Vec<MemberView> = Vec::with_capacity(ws.members.len());
    for m in &ws.members {
        let kind = map_kind(&m.kind);
        let lib_sources = match m.kind.lib_source() {
            Some(src) => collect_sources(&m.root, src, &m.name, &rewrite_root, &layout)?,
            None => Vec::new(),
        };
        let bin_sources = match m.kind.bin_source() {
            Some(src) => collect_sources(&m.root, src, &m.name, &rewrite_root, &layout)?,
            None => Vec::new(),
        };

        // Bin half include dirs: for a lib+bin member, the bin
        // needs the lib's own include dir for `#include "<crate>.h"`
        // (matches the existing `compile_one_module` extra_includes
        // shape). Cross-crate dep headers are reached via the
        // absolute paths baked by `#cust use <dep>` lowering, not
        // via `target_include_directories`.
        let bin_include_dirs = if kind == MemberKind::LibAndBin {
            vec![layout
                .crate_header_path(&m.name)
                .parent()
                .unwrap()
                .to_path_buf()]
        } else {
            Vec::new()
        };

        // Intra-workspace link deps for the bin half (V42D-13:
        // lower to `target_link_libraries`). Workspace deps come
        // from `Member::deps`; for lib+bin we additionally link
        // against the member's own lib half. TODO(slice B):
        // resolve the lib+bin self-link name collision — CMake
        // can't have two targets with the same name. Today's
        // cwork has no lib+bin members so the issue is dormant.
        let mut workspace_link_deps = m.deps.clone();
        if kind == MemberKind::LibAndBin {
            workspace_link_deps.insert(0, m.name.clone());
        }

        members.push(MemberView {
            name: m.name.clone(),
            kind,
            lib_sources,
            bin_sources,
            archive_output_dir: layout.build_dir(&m.name),
            bin_include_dirs,
            workspace_link_deps,
        });
    }

    Ok(WorkspaceView {
        cust_version: env!("CARGO_PKG_VERSION").to_string(),
        c_standard: "23".to_string(),
        plugin_path: plugin.map(|p| p.path.clone()),
        members,
    })
}

const fn map_kind(k: &CrateKind) -> MemberKind {
    match k {
        CrateKind::Lib { .. } => MemberKind::LibOnly,
        CrateKind::Bin { .. } => MemberKind::BinOnly,
        CrateKind::LibAndBin { .. } => MemberKind::LibAndBin,
    }
}

fn collect_sources(
    crate_root: &Path,
    entry_source: &Path,
    crate_name: &str,
    rewrite_root: &Path,
    layout: &TargetLayout,
) -> Result<Vec<SourceFile>> {
    let modules = modules::discover(crate_root, entry_source)
        .with_context(|| format!("discovering module graph for `{crate_name}`"))?;
    let mut out: Vec<SourceFile> = Vec::with_capacity(modules.len());
    for m in &modules {
        // Post-rewrite path: target/<profile>/.rewrite/<crate>/<rel>.
        // <rel> is the source's path relative to the crate root,
        // preserving src/<…>.c structure (V42D scope item shape +
        // design doc "Headline outcome" example).
        let rel = m
            .source_path
            .strip_prefix(crate_root)
            .unwrap_or(&m.source_path);
        let rewrite_path = rewrite_root.join(crate_name).join(rel);

        // OBJECT_DEPENDS: every `#cust use crate::<importee>`
        // edge resolves to the importee's fragment header.
        // V42D-4 wants topological order; slice A uses source-
        // declaration order from the scanner (matches topo in
        // practice for non-cyclic graphs, which V40D-11 already
        // requires for fragment convergence).
        let object_depends = m
            .imports
            .iter()
            .map(|importee| layout.fragment_path(crate_name, importee))
            .collect();

        out.push(SourceFile {
            path: rewrite_path,
            object_depends,
        });
    }
    Ok(out)
}

/// Write the workspace's `CMakeLists` into the build tree
/// (V42D-13 path + V42D-8 configure-skip stamp). Slice A's
/// only on-disk side effect for the CMake-driver work.
///
/// `build_workspace` calls this after computing `to_build` but
/// before running the per-member loop. The return value is
/// discarded today (slice A's wire is fire-and-forget); slice B
/// will branch on `WriteOutcome` to decide whether to re-run
/// `cmake -G Ninja`.
pub fn emit_workspace_cmakelists(
    ws: &Workspace,
    profile_kind: ProfileKind,
    plugin: Option<&Plugin>,
) -> Result<WriteOutcome> {
    let view = collect_view(ws, profile_kind, plugin)?;
    let bytes = generate(&view).into_bytes();
    let layout = TargetLayout::for_workspace(&ws.root, profile_kind);
    let cmake_dir = layout.profile_root.join("cmake");
    let cmakelists = cmake_dir.join("CMakeLists.txt");
    let stamp = cmake_dir.join("stamp").join("cmakelists.sha256");
    write_if_changed(&cmakelists, &bytes, &stamp, view.plugin_path.as_deref())
}

#[cfg(test)]
mod tests;
