//! `Cust.lock` schema and emission.
//!
//! v0.3 (V3D-8 in `docs/design/v0.3.md`) emits a minimal lock at
//! the workspace root containing the resolved member list and
//! their edges. There are no version pins or source hashes
//! because path deps don't need them; those land in v0.4
//! alongside registry deps.
//!
//! The schema is the v1 draft of the permanent contract
//! documented at `docs/spec/cust-lock.md`. v0.4 *extends* the
//! schema with per-dep `[[dep.source]]` entries; the format
//! version bumps to `2` only if a non-additive change forces it
//! (per cust-design.md §16 OQ-12).
//!
//! Top-level shape:
//!
//! ```toml
//! lock_format_version = 1
//! workspace_root = "/abs/path/at/lock/time"
//!
//! [[member]]
//! name = "app"
//! version = "0.1.0"
//! path = "app"               # workspace-root-relative
//! dependencies = ["util"]    # names only — paths are implied
//!                            # by each target member's own entry
//!
//! [[member]]
//! name = "util"
//! version = "0.1.0"
//! path = "util"
//! dependencies = []
//! ```
//!
//! Members are written in **alphabetical order by name** rather
//! than declaration order — so the on-disk content is independent
//! of which member happened to be the implicit root.
//!
//! The lock is only emitted for **real workspaces** (those with a
//! `[workspace]` table). A single-crate non-workspace project
//! has no edges to record, so no lock is written.

use std::{fmt::Write as _, fs, path::Path};

use anyhow::{Context, Result};

use crate::workspace::Workspace;

/// File name of the workspace lock file, sibling to the workspace
/// root's `Cust.toml`.
pub const LOCK_FILE: &str = "Cust.lock";

/// The format-version field's current value. v0.4 will either
/// keep this at 1 (additive extension) or bump to 2.
const LOCK_FORMAT_VERSION: u32 = 1;

/// Write `Cust.lock` for the given workspace, if it's a real
/// (non-degenerate) workspace. Returns the lock's absolute path
/// when a lock is written, `None` for single-crate projects
/// where no lock makes sense.
///
/// Idempotent: re-writes only when the rendered content differs
/// from what's on disk, so the file's mtime stays stable across
/// no-op builds.
pub fn write_lock(ws: &Workspace) -> Result<Option<std::path::PathBuf>> {
    if !ws.is_real_workspace() {
        return Ok(None);
    }
    let path = ws.root.join(LOCK_FILE);
    let body = render(ws);
    let needs_write = fs::read_to_string(&path).map_or(true, |existing| existing != body);
    if needs_write {
        fs::write(&path, body).with_context(|| format!("writing `{}`", path.display()))?;
    }
    Ok(Some(path))
}

/// Pure helper: render a workspace as the lock's TOML body.
/// Separated from `write_lock` so the unit tests don't need a
/// real filesystem (and so v0.4 can extend the schema by adding
/// to `render` without touching the I/O code).
fn render(ws: &Workspace) -> String {
    let mut out = String::new();
    out.push_str("# @generated by cust — DO NOT EDIT by hand.\n");
    out.push_str("# This file records the resolved workspace member graph.\n");
    out.push_str("# v0.3: path deps only; no version pins or source hashes.\n\n");
    let _ = writeln!(out, "lock_format_version = {LOCK_FORMAT_VERSION}");
    let _ = writeln!(
        out,
        "workspace_root = {}",
        toml_string(&ws.root.display().to_string())
    );

    // Sort members alphabetically so the on-disk order is stable
    // across runs and independent of declaration order.
    let mut members: Vec<&crate::workspace::Member> = ws.members.iter().collect();
    members.sort_by(|a, b| a.name.cmp(&b.name));

    for m in members {
        out.push('\n');
        out.push_str("[[member]]\n");
        let _ = writeln!(out, "name = {}", toml_string(&m.name));
        let version = m
            .manifest
            .package
            .as_ref()
            .map_or("", |p| p.version.as_str());
        let _ = writeln!(out, "version = {}", toml_string(version));
        // Path is rendered workspace-root-relative when possible
        // (always the case for normal layouts; canonicalisation
        // through symlinks could in principle produce a path
        // outside the root, but the resolver rejects those).
        let rel = m
            .root
            .strip_prefix(&ws.root)
            .map_or_else(|_| m.root.clone(), Path::to_path_buf);
        // Implicit root member has a zero-length relative path —
        // render as "." so the lock stays a valid TOML string.
        let rel_str = if rel.as_os_str().is_empty() {
            ".".to_string()
        } else {
            rel.to_string_lossy().into_owned()
        };
        let _ = writeln!(out, "path = {}", toml_string(&rel_str));

        // Dependencies sorted alphabetically (declaration order
        // doesn't matter for the lock; alphabetical keeps diffs
        // minimal across edits).
        let mut deps: Vec<&String> = m.deps.iter().collect();
        deps.sort();
        out.push_str("dependencies = [");
        for (i, d) in deps.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&toml_string(d));
        }
        out.push_str("]\n");
    }

    out
}

/// TOML string literal. Uses basic strings (double-quoted) with
/// backslash-escaping for `"` and `\`. Tab/newline/CR are also
/// escaped. Other ASCII controls are encoded as `\uXXXX`. Any
/// other character (including UTF-8) is passed through.
fn toml_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write as _;

    fn write(dir: &Path, rel: &str, content: &str) -> std::path::PathBuf {
        let path = dir.join(rel);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        let mut f = fs::File::create(&path).unwrap();
        f.write_all(content.as_bytes()).unwrap();
        path
    }

    fn stage_workspace(tmp: &Path) {
        write(
            tmp,
            "Cust.toml",
            "[workspace]\nmembers = [\"app\", \"util\"]\n",
        );
        write(
            tmp,
            "app/Cust.toml",
            "[package]\nname = \"app\"\nversion = \"0.2.1\"\n\
             [dependencies]\nutil = { path = \"../util\" }\n",
        );
        write(tmp, "app/src/lib.c", "int a = 1;\n");
        write(
            tmp,
            "util/Cust.toml",
            "[package]\nname = \"util\"\nversion = \"0.1.0\"\n",
        );
        write(tmp, "util/src/lib.c", "int u = 1;\n");
    }

    #[test]
    fn render_has_format_version_and_workspace_root() {
        let tmp = tempfile::tempdir().unwrap();
        stage_workspace(tmp.path());
        let ws = Workspace::discover(tmp.path()).unwrap();
        let body = render(&ws);
        assert!(body.contains("lock_format_version = 1"), "{body}");
        assert!(body.contains("workspace_root = \""), "{body}");
    }

    #[test]
    fn render_lists_members_alphabetically() {
        let tmp = tempfile::tempdir().unwrap();
        stage_workspace(tmp.path());
        let ws = Workspace::discover(tmp.path()).unwrap();
        let body = render(&ws);
        let app_pos = body.find("name = \"app\"").unwrap();
        let util_pos = body.find("name = \"util\"").unwrap();
        assert!(app_pos < util_pos, "members not alphabetical:\n{body}");
    }

    #[test]
    fn render_records_dep_edge_and_version() {
        let tmp = tempfile::tempdir().unwrap();
        stage_workspace(tmp.path());
        let ws = Workspace::discover(tmp.path()).unwrap();
        let body = render(&ws);
        assert!(body.contains("name = \"app\""), "{body}");
        assert!(body.contains("version = \"0.2.1\""), "{body}");
        assert!(body.contains("dependencies = [\"util\"]"), "{body}");
        // util has no deps -> empty array.
        // Check by locating util's section and ensuring its deps
        // line is `[]`.
        let util_section = body
            .split("[[member]]")
            .find(|s| s.contains("name = \"util\""))
            .unwrap();
        assert!(util_section.contains("dependencies = []"), "{util_section}");
    }

    #[test]
    fn implicit_root_member_renders_path_as_dot() {
        let tmp = tempfile::tempdir().unwrap();
        // Root is also a member: both [package] and [workspace].
        write(
            tmp.path(),
            "Cust.toml",
            "[package]\nname = \"root\"\nversion = \"0.1.0\"\n\
             [workspace]\nmembers = [\"util\"]\n",
        );
        write(tmp.path(), "src/lib.c", "int r = 1;\n");
        write(
            tmp.path(),
            "util/Cust.toml",
            "[package]\nname = \"util\"\nversion = \"0.1.0\"\n",
        );
        write(tmp.path(), "util/src/lib.c", "int u = 1;\n");

        let ws = Workspace::discover(tmp.path()).unwrap();
        let body = render(&ws);
        // root's path becomes ".".
        let root_section = body
            .split("[[member]]")
            .find(|s| s.contains("name = \"root\""))
            .unwrap();
        assert!(root_section.contains("path = \".\""), "{root_section}");
    }

    #[test]
    fn write_lock_emits_file_for_real_workspace() {
        let tmp = tempfile::tempdir().unwrap();
        stage_workspace(tmp.path());
        let ws = Workspace::discover(tmp.path()).unwrap();
        let path = write_lock(&ws)
            .unwrap()
            .expect("real workspace must emit lock");
        assert_eq!(path, tmp.path().canonicalize().unwrap().join(LOCK_FILE));
        let body = fs::read_to_string(&path).unwrap();
        assert!(body.contains("lock_format_version = 1"), "{body}");
    }

    #[test]
    fn write_lock_skips_single_crate() {
        let tmp = tempfile::tempdir().unwrap();
        write(
            tmp.path(),
            "Cust.toml",
            "[package]\nname = \"solo\"\nversion = \"0.1.0\"\n",
        );
        write(tmp.path(), "src/lib.c", "int x = 1;\n");
        let ws = Workspace::discover(tmp.path()).unwrap();
        let result = write_lock(&ws).unwrap();
        assert!(result.is_none(), "single-crate produced a lock");
        assert!(!tmp.path().join(LOCK_FILE).exists());
    }

    #[test]
    fn write_lock_is_idempotent_on_no_op() {
        let tmp = tempfile::tempdir().unwrap();
        stage_workspace(tmp.path());
        let ws = Workspace::discover(tmp.path()).unwrap();
        let path = write_lock(&ws).unwrap().unwrap();
        let mtime1 = fs::metadata(&path).unwrap().modified().unwrap();
        // Second write with identical content must NOT touch the
        // file (mtime check). Sleep a hair to make the test
        // robust on filesystems with coarse mtime resolution.
        std::thread::sleep(std::time::Duration::from_millis(20));
        write_lock(&ws).unwrap();
        let mtime2 = fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(mtime1, mtime2, "lock file rewritten unnecessarily");
    }

    #[test]
    fn toml_string_escapes_quote_and_backslash() {
        assert_eq!(toml_string("hi"), "\"hi\"");
        assert_eq!(toml_string("a\"b"), "\"a\\\"b\"");
        assert_eq!(toml_string("a\\b"), "\"a\\\\b\"");
        assert_eq!(toml_string("a\nb"), "\"a\\nb\"");
        assert_eq!(toml_string("\u{07}"), "\"\\u0007\"");
    }
}
