// cust clang plugin — surface-extraction pass.
//
// Walks a TU's top-level decls, picks out anything carrying
// `[[clang::annotate("cust::pub")]]` (placed there by the prelude's
// cust_pub macro), and emits forward declarations into a per-
// module fragment header.
//
// Invoked by the driver as:
//
//     clang ... -fplugin=libcust_plugin.so \
//                -fplugin-arg-cust-fragment-out=<path>
//
// If `fragment-out` is absent the plugin runs but writes nothing
// — handy for clangd / IDE invocations that just want the AST
// validation.
//
// Atomicity: writes go through a `<path>.tmp` + rename so half-
// written fragments can never be observed. If the byte content
// matches what's already on disk we skip the write entirely; this
// is the cust-design.md §4 fragment-stamping invariant that lets
// downstream modules avoid rebuilds when an importee's surface
// didn't change.

#include "clang/AST/ASTConsumer.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/Basic/AttributeCommonInfo.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendPluginRegistry.h"
#include "clang/Sema/ParsedAttr.h"
#include "clang/Sema/Sema.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"

#include <memory>
#include <string>
#include <system_error>
#include <vector>

using namespace clang;

namespace {

// True if `D` carries `[[clang::annotate("cust::pub")]]`.
bool hasCustPub(const Decl *D) {
    for (const auto *attr : D->specific_attrs<AnnotateAttr>()) {
        if (attr->getAnnotation() == "cust::pub") {
            return true;
        }
    }
    return false;
}

// Render one decl into its fragment-header form. Returns the
// empty string for kinds we don't know how to handle today.
std::string renderDecl(const Decl *D, ASTContext &ctx) {
    PrintingPolicy policy(ctx.getLangOpts());
    policy.TerseOutput = true;          // no function/var bodies
    policy.SuppressInitializers = true;
    policy.PolishForDeclaration = true;
    policy.SuppressTagKeyword = false;

    std::string out;
    llvm::raw_string_ostream os(out);

    if (const auto *fd = dyn_cast<FunctionDecl>(D)) {
        fd->print(os, policy);
        os << ";\n";
    } else if (const auto *td = dyn_cast<TypedefDecl>(D)) {
        // Prints as `typedef X name` — append `;` for a valid decl.
        td->print(os, policy);
        os << ";\n";
    } else if (const auto *rd = dyn_cast<RecordDecl>(D)) {
        // Opaque tag forward declaration. The body stays private
        // to the defining module (cust-design.md §4); `cust_pub`
        // *with* body export needs a future `cust_pub_repr` that
        // emits the full struct. Not yet.
        if (!rd->getIdentifier()) {
            return {}; // anonymous struct/union — skip
        }
        os << (rd->isUnion() ? "union " : "struct ");
        os << rd->getName() << ";\n";
    } else if (const auto *vd = dyn_cast<VarDecl>(D)) {
        // Variable declarations become `extern <type> <name>;`.
        os << "extern ";
        vd->print(os, policy);
        os << ";\n";
    } else {
        return {};
    }
    return out;
}

// Collect the fragment-header contents for one TU.
std::string buildFragmentContents(ASTContext &ctx) {
    std::string contents;
    contents += "/* @generated by cust plugin — DO NOT EDIT */\n";
    contents += "/* Forward declarations of [[cust::pub]] items. */\n\n";

    for (Decl *D : ctx.getTranslationUnitDecl()->decls()) {
        if (D->isImplicit()) {
            continue;
        }
        if (!hasCustPub(D)) {
            continue;
        }
        std::string s = renderDecl(D, ctx);
        if (!s.empty()) {
            contents += s;
        }
    }
    return contents;
}

// Atomic write with skip-on-identical. Returns true on success.
bool writeFragmentIfChanged(const std::string &path,
                            const std::string &contents,
                            DiagnosticsEngine &diags) {
    // Skip if existing file matches byte-for-byte.
    {
        auto existing = llvm::MemoryBuffer::getFile(path);
        if (existing &&
            llvm::StringRef((*existing)->getBuffer()) == contents) {
            return true;
        }
    }

    // Ensure parent directory exists.
    std::error_code ec =
        llvm::sys::fs::create_directories(llvm::sys::path::parent_path(path));
    if (ec) {
        auto id = diags.getCustomDiagID(
            DiagnosticsEngine::Error,
            "cust plugin: failed to create directory for %0: %1");
        diags.Report(id) << path << ec.message();
        return false;
    }

    std::string tmp = path + ".tmp";
    {
        llvm::raw_fd_ostream os(tmp, ec);
        if (ec) {
            auto id = diags.getCustomDiagID(
                DiagnosticsEngine::Error,
                "cust plugin: failed to open %0 for write: %1");
            diags.Report(id) << tmp << ec.message();
            return false;
        }
        os << contents;
        // ~raw_fd_ostream flushes + closes.
    }

    ec = llvm::sys::fs::rename(tmp, path);
    if (ec) {
        auto id = diags.getCustomDiagID(
            DiagnosticsEngine::Error,
            "cust plugin: failed to rename %0 to %1: %2");
        diags.Report(id) << tmp << path << ec.message();
        return false;
    }
    return true;
}

class CustASTConsumer : public ASTConsumer {
public:
    CustASTConsumer(CompilerInstance &ci, std::string fragmentOut)
        : CI(ci), FragmentOut(std::move(fragmentOut)) {}

    void HandleTranslationUnit(ASTContext &ctx) override {
        if (FragmentOut.empty()) {
            // Plugin loaded but driver passed no destination —
            // happens for clangd/IDE compilations that should
            // share flags but skip the fragment-header side
            // effect. Silent no-op.
            return;
        }
        std::string contents = buildFragmentContents(ctx);
        writeFragmentIfChanged(FragmentOut, contents, CI.getDiagnostics());
    }

private:
    CompilerInstance &CI;
    std::string FragmentOut;
};

// ---------------------------------------------------------------------------
// v0.4.0 slice A — `ParsedAttrInfo` recogniser for `[[cust::pub]]`.
//
// Dispatches on `getArg(0)` per V40D-7 (one recogniser per attribute name,
// not name + args — clang's `ParsedAttrInfoRegistry` registers by name).
// Both forms produce the same `AnnotateAttr` payload string that the
// existing `CustASTConsumer` / `hasCustPub` path already recognises, so
// the C23-attribute and macro spellings remain interchangeable through
// slices A–D; slice E retires the macros and removes the legacy
// `annotate("cust::*")` recognition.
//
// Decl-kind-aware visibility lift (V40D-7 bullet 3): when `[[cust::pub]]`
// (no modifier) is attached to a function or variable decl, the recogniser
// also attaches `VisibilityAttr(Default)` to lift the symbol over the
// crate-wide `-fvisibility=hidden`. Type decls (typedef/record/enum) get
// no visibility lift — visibility on a typedef warns
// (`-Wignored-attributes`), and tagged types have no linkage of their own
// anyway. This subsumes what cust_pub vs cust_pub_t encoded manually in
// the v0.3.x prelude.

struct CustPubAttrInfo : public ParsedAttrInfo {
    CustPubAttrInfo() {
        OptArgs = 1;
        NumArgs = 0;
        // `[[cust::pub]]` (C23 / C++11 attribute spelling).
        static constexpr Spelling kSpellings[] = {
            {ParsedAttr::AS_CXX11, "cust::pub"},
            {ParsedAttr::AS_C23, "cust::pub"},
        };
        Spellings = kSpellings;
    }

    bool diagAppertainsToDecl(Sema &S, const ParsedAttr &Attr,
                              const Decl *D) const override {
        if (!isa<FunctionDecl>(D) && !isa<VarDecl>(D) &&
            !isa<TypedefDecl>(D) && !isa<RecordDecl>(D) && !isa<EnumDecl>(D)) {
            unsigned id = S.getDiagnostics().getCustomDiagID(
                DiagnosticsEngine::Error,
                "`[[cust::pub]]` only applies to functions, variables, "
                "typedefs, structs, unions, and enums");
            S.Diag(Attr.getLoc(), id);
            return false;
        }
        return true;
    }

    AttrHandling handleDeclAttribute(Sema &S, Decl *D,
                                     const ParsedAttr &Attr) const override {
        llvm::StringRef payload;
        bool plainPub = false;

        if (Attr.getNumArgs() == 0) {
            payload = "cust::pub";
            plainPub = true;
        } else if (Attr.getNumArgs() == 1) {
            if (!Attr.isArgIdent(0)) {
                unsigned id = S.getDiagnostics().getCustomDiagID(
                    DiagnosticsEngine::Error,
                    "`[[cust::pub]]` modifier must be an identifier "
                    "(`crate` or `repr`)");
                S.Diag(Attr.getLoc(), id);
                return AttributeNotApplied;
            }
            llvm::StringRef arg =
                Attr.getArgAsIdent(0)->getIdentifierInfo()->getName();
            if (arg == "crate") {
                payload = "cust::pub_crate";
            } else if (arg == "repr") {
                payload = "cust::pub_repr";
            } else {
                unsigned id = S.getDiagnostics().getCustomDiagID(
                    DiagnosticsEngine::Error,
                    "unknown `pub` modifier `%0`; expected `crate` or `repr`");
                S.Diag(Attr.getLoc(), id) << arg;
                return AttributeNotApplied;
            }
        } else {
            unsigned id = S.getDiagnostics().getCustomDiagID(
                DiagnosticsEngine::Error,
                "`[[cust::pub]]` takes 0 or 1 arguments, got %0");
            S.Diag(Attr.getLoc(), id) << Attr.getNumArgs();
            return AttributeNotApplied;
        }

        ASTContext &ctx = S.getASTContext();
        D->addAttr(AnnotateAttr::Create(ctx, payload.str(),
                                        /*Args=*/nullptr, /*NumArgs=*/0,
                                        Attr.getRange()));

        // Decl-kind-aware visibility lift. Only plain `[[cust::pub]]` on
        // a function or variable; type decls and `pub(crate)` / `pub(repr)`
        // don't lift.
        if (plainPub && (isa<FunctionDecl>(D) || isa<VarDecl>(D))) {
            D->addAttr(VisibilityAttr::CreateImplicit(
                ctx, VisibilityAttr::Default, Attr.getRange()));
        }

        return AttributeApplied;
    }
};

class CustPluginAction : public PluginASTAction {
protected:
    std::unique_ptr<ASTConsumer> CreateASTConsumer(CompilerInstance &CI,
                                                   llvm::StringRef) override {
        return std::make_unique<CustASTConsumer>(CI, FragmentOut);
    }

    bool ParseArgs(const CompilerInstance &CI,
                   const std::vector<std::string> &args) override {
        static constexpr llvm::StringRef kFragOut = "fragment-out=";
        for (const auto &a : args) {
            llvm::StringRef sa = a;
            if (sa.starts_with(kFragOut)) {
                FragmentOut = sa.drop_front(kFragOut.size()).str();
            } else {
                auto &diags = CI.getDiagnostics();
                auto id = diags.getCustomDiagID(
                    DiagnosticsEngine::Warning,
                    "cust plugin: unknown arg %0 (ignored)");
                diags.Report(id) << a;
            }
        }
        return true;
    }

    // Run automatically every time the host frontend action runs,
    // matching the `-fplugin=...` invoker convention.
    PluginASTAction::ActionType getActionType() override {
        return AddBeforeMainAction;
    }

private:
    std::string FragmentOut;
};

} // namespace

static FrontendPluginRegistry::Add<CustPluginAction>
    X("cust", "cust clang plugin (surface extraction)");

static ParsedAttrInfoRegistry::Add<CustPubAttrInfo>
    Y("cust_pub", "cust [[cust::pub]] attribute recogniser (V40D-7)");
